--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/10/2023 10:25:10 AM
-- Server version: 8.0.32
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `misa.amis.mf1545.pvbien`;

--
-- Drop procedure `Proc_Employee_Delete`
--
DROP PROCEDURE IF EXISTS Proc_Employee_Delete;

--
-- Drop procedure `Proc_Employee_Deletes`
--
DROP PROCEDURE IF EXISTS Proc_Employee_Deletes;

--
-- Drop procedure `Proc_Employee_ExportExcel`
--
DROP PROCEDURE IF EXISTS Proc_Employee_ExportExcel;

--
-- Drop procedure `Proc_Employee_GetByEmployeeCode`
--
DROP PROCEDURE IF EXISTS Proc_Employee_GetByEmployeeCode;

--
-- Drop procedure `Proc_Employee_GetByFilter`
--
DROP PROCEDURE IF EXISTS Proc_Employee_GetByFilter;

--
-- Drop procedure `Proc_Employee_GetById`
--
DROP PROCEDURE IF EXISTS Proc_Employee_GetById;

--
-- Drop procedure `Proc_Employee_GetMaxCode`
--
DROP PROCEDURE IF EXISTS Proc_Employee_GetMaxCode;

--
-- Drop procedure `Proc_Employee_Insert`
--
DROP PROCEDURE IF EXISTS Proc_Employee_Insert;

--
-- Drop procedure `Proc_Employee_Update`
--
DROP PROCEDURE IF EXISTS Proc_Employee_Update;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop procedure `Proc_Department_GetByFilter`
--
DROP PROCEDURE IF EXISTS Proc_Department_GetByFilter;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Set default database
--
USE `misa.amis.mf1545.pvbien`;

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmentId char(36) NOT NULL DEFAULT '' COMMENT 'Mã phòng ban',
  DepartmentName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên phòng ban',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedBy varchar(255) DEFAULT NULL COMMENT 'Người tạo',
  ModifiedDate timestamp NULL DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedBy varchar(255) DEFAULT NULL COMMENT 'Người sửa',
  PRIMARY KEY (DepartmentId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Thông tin phòng ban';

DELIMITER $$

--
-- Create procedure `Proc_Department_GetByFilter`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Department_GetByFilter (IN p_PageSize int, IN p_PageNumber int)
BEGIN
  -- Hàm lấy danh sách đơn vị theo phân trang --
  -- CreatedBy: Bien (25/02/2023)--
  SET @PageIndex = p_PageNumber;
  SET @PageSize = p_PageSize;
  CREATE TEMPORARY TABLE IF NOT EXISTS tbDepartmentOrginal AS
  SELECT
    ROW_NUMBER() OVER (
    ORDER BY CreatedDate DESC) AS RowIndex,
    d.DepartmentId,
    d.DepartmentName
  FROM Department d;
  SET @IndexEnd = @PageIndex * @PageSize;
  SET @IndexStart = @IndexEnd - @PageSize + 1;

  -- Câu lệnh lấy danh sách đơn vị --
  SELECT
    eo.DepartmentId,
    eo.DepartmentName
  FROM tbDepartmentOrginal eo
  WHERE eo.RowIndex BETWEEN @IndexStart AND @IndexEnd;

  -- Câu lệnh lấy tổng sô đơn vị --
  SELECT
    COUNT(*)
  FROM tbDepartmentOrginal d;
  DROP TEMPORARY TABLE IF EXISTS tbDepartmentOrginal;
END
$$

DELIMITER ;

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeId char(36) NOT NULL DEFAULT '' COMMENT 'Khóa chính của bản nhân viên',
  EmployeeCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã nhân viên',
  FullName varchar(100) NOT NULL DEFAULT '' COMMENT 'Tên nhân viên',
  DateOfBirth date DEFAULT NULL COMMENT 'Ngày tháng năm sinh',
  Gender int DEFAULT NULL COMMENT 'Giới tính (0 - Nam, 1 - Nữ, 2 - Khác)',
  LandlineNumber varchar(50) DEFAULT NULL COMMENT 'Điện thoại cố định',
  PhoneNumber varchar(50) DEFAULT NULL COMMENT 'Điện thoại di động',
  Email varchar(100) DEFAULT NULL COMMENT 'Địa chỉ email',
  Address varchar(255) DEFAULT NULL COMMENT 'Địa chỉ',
  IdentityNumber varchar(25) DEFAULT NULL COMMENT 'Số chúng minh nhân dân(Căn cước công dân)',
  IdentityDate date DEFAULT NULL COMMENT 'Ngày cấp',
  IdentityPlace varchar(255) DEFAULT NULL COMMENT 'Nơi cấp',
  Position varchar(100) DEFAULT NULL COMMENT 'Chức danh',
  BankAccount varchar(25) DEFAULT NULL COMMENT 'Số tài khoản ngân hàng',
  BankName varchar(255) DEFAULT NULL COMMENT 'Tên ngân hàng',
  BankBranch varchar(255) DEFAULT NULL COMMENT 'Chi nhánh ngân hàng',
  DepartmentId char(36) DEFAULT NULL COMMENT 'Mã phòng ban(Khóa ngoài)',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedBy varchar(255) DEFAULT NULL COMMENT 'Người tạo',
  ModifiedDate timestamp NULL DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedBy varchar(255) DEFAULT NULL COMMENT 'Người sửa',
  EmployeeIndex int DEFAULT NULL,
  PRIMARY KEY (EmployeeId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 479,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Thông tin nhân viên';

--
-- Create index `IDX_Employee_FullName` on table `employee`
--
ALTER TABLE employee
ADD INDEX IDX_Employee_FullName (FullName);

--
-- Create index `UK_Employee_EmployeeCode` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX UK_Employee_EmployeeCode (EmployeeCode);

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_Employee_DepartmentId FOREIGN KEY (DepartmentId)
REFERENCES department (DepartmentId);

DELIMITER $$

--
-- Create procedure `Proc_Employee_Update`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Employee_Update (IN p_EmployeeId char(36), IN p_EmployeeCode varchar(20), IN p_FullName varchar(100), IN p_DateOfBirth date, IN p_Gender int, IN p_LandlineNumber varchar(50), IN p_PhoneNumber varchar(50), IN p_Email varchar(100), IN p_Address varchar(255), IN p_IdentityNumber varchar(25), IN p_IdentityDate date, IN p_IdentityPlace varchar(255), IN p_Position varchar(100), IN p_BankAccount varchar(25), IN p_BankName varchar(255), IN p_BankBranch varchar(255), IN p_DepartmentId char(36))
BEGIN
  -- Câu lệnh sửa nhân viên--
  -- CreatedBy: Bien (25/02/2023 ) --
  UPDATE Employee e
  SET EmployeeId = p_EmployeeId,
      EmployeeCode = p_EmployeeCode,
      FullName = p_FullName,
      DateOfBirth = p_DateOfBirth,
      Gender = p_Gender,
      LandlineNumber = p_LandlineNumber,
      PhoneNumber = p_PhoneNumber,
      Email = p_Email,
      Address = p_Address,
      IdentityNumber = p_IdentityNumber,
      IdentityDate = p_IdentityDate,
      IdentityPlace = p_IdentityPlace,
      Position = p_Position,
      BankAccount = p_BankAccount,
      BankName = p_BankName,
      BankBranch = p_BankBranch,
      DepartmentId = p_DepartmentId,
      ModifiedDate = NOW(),
      ModifiedBy = 'Admin'
  WHERE EmployeeId = p_EmployeeId;
END
$$

--
-- Create procedure `Proc_Employee_Insert`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Employee_Insert (IN EmployeeCode varchar(20), IN FullName varchar(100), IN DateOfBirth date, IN Gender int, IN LandlineNumber varchar(50), IN PhoneNumber varchar(50), IN Email varchar(100), IN Address varchar(255), IN IdentityNumber varchar(25), IN IdentityDate date, IN IdentityPlace varchar(255), IN Position varchar(100), IN BankAccount varchar(25), IN BankName varchar(255), IN BankBranch varchar(255), IN DepartmentId char(36))
BEGIN
  -- Câu lệnh thêm nhân viên --
  -- CreatedBy: Bien (25/02/2023 ) --
  INSERT INTO Employee (EmployeeId, EmployeeCode, FullName, DateOfBirth, Gender, LandlineNumber, PhoneNumber, Email, Address, IdentityNumber, IdentityDate, IdentityPlace, Position, BankAccount, BankName, BankBranch, DepartmentId, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy)
    VALUES (UUID(), EmployeeCode, FullName, DateOfBirth, Gender, LandlineNumber, PhoneNumber, Email, Address, IdentityNumber, IdentityDate, IdentityPlace, Position, BankAccount, BankName, BankBranch, DepartmentId, NOW(), '', NOW(), '');

END
$$

--
-- Create procedure `Proc_Employee_GetMaxCode`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Employee_GetMaxCode ()
BEGIN
  -- Câu lệnh lấy giá trị lớn nhất của mã nhân viên --
  -- CreatedBy: Bien (25/02/2023 ) --
  -- Câu lệnh lấy giá trị lớn nhất của phần số trong mã
  SELECT
    MAX(e.EmployeeCode)
  FROM employee e;
END
$$

--
-- Create procedure `Proc_Employee_GetById`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Employee_GetById (IN p_EmployeeId char(36))
BEGIN
  -- Câu lệnh lấy nhân viên theo id --
  -- CreatedBy: Bien (25/02/2023 ) --
  SELECT
    *
  FROM Employee e
  WHERE e.EmployeeId = p_EmployeeId;
END
$$

--
-- Create procedure `Proc_Employee_GetByFilter`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Employee_GetByFilter (IN p_PageSize int, IN p_PageNumber int, IN p_EmployeeFilter varchar(100))
BEGIN
  -- Câu lệnh lấy danh sách nhân viên theo phân trang và tìm kiếm --
  -- CreatedBy: Bien (25/02/2023 )--
  SET @PageIndex = p_PageNumber;
  SET @PageSize = p_PageSize;
  SET @Keyword = CONCAT('%', p_EmployeeFilter, '%');
  CREATE TEMPORARY TABLE IF NOT EXISTS tbEmployeeOrginal AS
  SELECT
    ROW_NUMBER() OVER (
    ORDER BY CreatedDate DESC) AS RowIndex,
    e.EmployeeId,
    e.EmployeeCode,
    e.FullName,
    e.DateOfBirth,
    e.Gender,
    CASE WHEN e.Gender = 0 THEN "Nam" WHEN e.Gender = 1 THEN "Nữ" ELSE "Khác" END AS GenderName,
    e.CreatedDate,
    e.CreatedBy,
    e.ModifiedDate,
    e.ModifiedBy,
    e.LandlineNumber,
    e.PhoneNumber,
    e.Email,
    e.Address,
    e.IdentityNumber,
    e.IdentityDate,
    e.IdentityPlace,
    e.Position,
    e.BankAccount,
    e.BankName,
    e.BankBranch,
    e.EmployeeIndex,
    d.DepartmentId,
    d.DepartmentName
  FROM Employee e
    LEFT JOIN Department d
      ON e.DepartmentId = d.DepartmentId
  WHERE (e.FullName LIKE @Keyword
  OR e.EmployeeCode LIKE @Keyword
  OR p_EmployeeFilter = ''
  OR p_EmployeeFilter IS NULL);
  SET @IndexEnd = @PageIndex * @PageSize;
  SET @IndexStart = @IndexEnd - @PageSize + 1;
  -- Câu lệnh lấy danh sách nhân viên --
  SELECT
    *
  FROM tbEmployeeOrginal eo
  WHERE eo.RowIndex BETWEEN @IndexStart AND @IndexEnd;
  -- Câu lệnh lấy tổng số nhân viên --
  SELECT
    COUNT(*)
  FROM tbEmployeeOrginal;
  DROP TEMPORARY TABLE IF EXISTS tbEmployeeOrginal;
END
$$

--
-- Create procedure `Proc_Employee_GetByEmployeeCode`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Employee_GetByEmployeeCode (IN p_EmployeeCode varchar(20))
BEGIN
  -- Câu lệnh kiểm tra mã nhân viên đã tồn tại  --
  -- CreatedBy: Bien (25/02/2023) --
  SELECT
    e.EmployeeId
  FROM Employee e
  WHERE e.EmployeeCode = p_EmployeeCode;
END
$$

--
-- Create procedure `Proc_Employee_ExportExcel`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Employee_ExportExcel (IN p_EmployeeFilter varchar(100))
BEGIN
  -- Câu lệnh xuất khẩu dữ liệu nhân viên --
  -- CreatedBy: Bien (25/02/2023)--
  SET @Keyword = CONCAT('%', p_EmployeeFilter, '%');
  CREATE TEMPORARY TABLE IF NOT EXISTS tbEmployeeOrginal AS
  SELECT
    ROW_NUMBER() OVER (
    ORDER BY CreatedDate DESC) AS RowIndex,
    e.EmployeeId,
    e.EmployeeCode,
    e.FullName,
    e.DateOfBirth,
    e.Gender,
    CASE WHEN e.Gender = 0 THEN "Nam" WHEN e.Gender = 1 THEN "Nữ" ELSE "Khác" END AS GenderName,
    e.CreatedDate,
    e.CreatedBy,
    e.ModifiedDate,
    e.ModifiedBy,
    e.LandlineNumber,
    e.PhoneNumber,
    e.Email,
    e.Address,
    e.IdentityNumber,
    e.IdentityDate,
    e.IdentityPlace,
    e.Position,
    e.BankAccount,
    e.BankName,
    e.BankBranch,
    e.EmployeeIndex,
    d.DepartmentId,
    d.DepartmentName
  FROM Employee e
    LEFT JOIN Department d
      ON e.DepartmentId = d.DepartmentId
  WHERE (e.FullName LIKE @Keyword
  OR e.EmployeeCode LIKE @Keyword
  OR p_EmployeeFilter = ''
  OR p_EmployeeFilter IS NULL);

  -- Câu lệnh lấy danh sách nhân viên --
  SELECT
    *
  FROM tbEmployeeOrginal eo;

  -- Câu lệnh lấy tổng số nhân viên --
  SELECT
    COUNT(*)
  FROM tbEmployeeOrginal;
  DROP TEMPORARY TABLE IF EXISTS tbEmployeeOrginal;
END
$$

--
-- Create procedure `Proc_Employee_Deletes`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Employee_Deletes (IN p_EmployeeIds text)
BEGIN
  -- Câu lệnh xóa nhiều nhân viên --
  -- CreatedBy: Bien (25/02/2023)--
  DELETE
    FROM employee
  WHERE FIND_IN_SET(EmployeeId, p_EmployeeIds);
END
$$

--
-- Create procedure `Proc_Employee_Delete`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Employee_Delete (IN p_EmployeeId char(36))
BEGIN
  -- Câu lệnh xóa nhân viên --
  -- CreatedBy: Bien (25/02/2023)--
  DELETE LOW_PRIORITY QUICK
    FROM Employee
  WHERE EmployeeId = p_EmployeeId;
END
$$

DELIMITER ;

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES
('11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Phòng nhân sự', '2021-04-15 04:35:00', 'Adolph Francisco', '2021-09-13 08:59:38', 'Jason Blackmon'),
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'Phòng kinh doanh', '2022-01-01 00:07:13', 'Letha Bolt', '2022-01-01 00:07:13', 'Abraham Acevedo'),
('17120d02-6ab5-3e43-18cb-66948daf6128', 'Phòng quản lý', '2005-05-09 18:38:02', 'Miyoko Mckinney', '1973-10-01 23:07:47', 'Hong Beaudoin'),
('469b3ece-744a-45d5-957d-e8c757976496', 'Phòng kế toán', '2022-04-17 21:54:11', 'Vanita Kelleher', '2022-08-23 23:04:49', 'Retta Lord'),
('4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Phòng công nghệ thông tin', '2023-12-15 05:57:36', 'Marcos Abraham', '2023-05-03 14:36:20', 'Treena Lind'),
('768f8e64-7d10-20c9-967d-e8c757976496', 'Phòng sản xuất', '1996-03-13 03:52:43', 'Oma Lawler', '2000-03-24 17:43:44', 'Tiny Card');

-- 
-- Dumping data for table employee
--
INSERT INTO employee VALUES
('11a8748f-3464-740c-28c2-579daad24557', 'NV-23373', 'Trần Linh Thoa', '1962-12-11', 0, '0987419510', '0987419510', 'Almeida24@example.com', '104A Tân Chánh Hiệp 10', '495799941491', '2012-08-03', '201/60/12 Nguyễn Xí', 'Giám đốc', '52663', 'MBBank', '3c/144 quan nhân', '768f8e64-7d10-20c9-967d-e8c757976496', '1970-01-01 01:00:32', 'Glynis Battle', '1971-01-01 01:00:32', 'Andrew Crutchfield', NULL),
('12693b29-274c-35ce-d11d-086412a8ea97', 'NV-00572', 'Nguyễn Việt Vinh', '1966-03-18', 2, '0369878969', '0963369896', 'EleanoreYEscamilla158@example.com', '117 Thịnh Quang', '173020325360', '2012-12-20', '36 Thạch Yên', 'Trường phòng', '87829', 'ACBank', '697 Vũ Tông Phan', '768f8e64-7d10-20c9-967d-e8c757976496', '1995-10-26 18:45:47', 'Cody Feliciano', '1973-09-13 01:44:48', 'Adolfo Rangel', NULL),
('12e12a5c-6e3a-503a-d71d-086412a8ea97', 'NV-02194', 'Nguyễn Ánh Quỳnh', '1999-12-14', 0, '0369877415', '0369878969', 'Dana.Buckner@nowhere.com', 'Số 37 DV2 khu đô thị văn phú', '097840781170', '2010-10-11', '173 Văn Chương', 'Nhân viên', '15532', 'MBBank', 'Số 3 ngõ 13 Lĩnh Nam', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2006-02-10 04:39:39', 'Noel Acevedo', '1975-01-23 01:22:28', 'Alfonso Macklin', NULL),
('12e1b096-3542-127a-1077-d9ebc53aac3d', 'NV-08240', 'Nguyễn Ngọc Loan', '1971-09-19', 0, '0369878963', '0369878969', 'Abel5@example.com', 'B240 ĐHT 11', '296010804270', '2019-07-16', '118 Đông Hưng Thuận 06', 'Nhân viên', '91427', 'Vietcombank', '33B Phạm Ngũ Lão', '768f8e64-7d10-20c9-967d-e8c757976496', '2011-12-01 04:43:14', 'Freeda Brinkley', '1984-12-13 08:15:33', 'Avery Weeks', NULL),
('13ede5b6-19dd-563e-1980-de64d090a2c2', 'NV-92666', 'Trần Khánh Giang', '1987-12-30', 2, '0369989699', '0986369879', 'ElmerFoley@example.com', '697 Vũ Tông Phan', '154846275030', '2021-05-10', 'số 2 Nguyễn Hiền', 'Nhân viên', '95191', 'ACBank', '78 Trương Văn Thành', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2011-01-11 20:57:27', 'Tory Olson', '2013-05-08 02:42:50', 'Clemmie Grove', NULL),
('143e4110-751a-5474-1f80-de64d090a2c2', 'NV-28695', 'Nguyễn Hưng Danh', '1969-07-07', 0, '0369989699', '0369878963', 'irylvc2@nowhere.com', '95/33 Lê Tấn Bê', '806551228501', '2021-12-26', '95 Tân Lập 1', 'Giám đốc', '07221', 'ACBank', '58 Lâm Thị Hố', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1970-01-01 01:40:32', 'Jong Dancy', '1971-01-01 01:40:32', 'Vanetta Acevedo', NULL),
('14aa1334-3d35-32c4-30c2-579daad24557', 'NV-85279', 'Hồ Quốc Dương', '1985-11-06', 0, '0369878969', '0986369879', 'Bernardo_Nance35@example.com', '60/15 Vạn Kiếp', '204786493640', '2020-01-01', '234/28 Phạm Văn Hân', 'Bảo vệ', '76672', 'MBBank', 'Số 19 ngõ 565 lạc long quân', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1973-10-19 15:25:39', 'Sidney Hennessey', '2006-04-10 13:38:12', 'Olen Frey', NULL),
('1518ced5-6993-37f8-6180-7ed9d1ea06ea', 'NV-95190', 'Trần Thị Hiền', '1981-01-24', 2, '0369878969', '0987419510', 'Mitchel.Taylor6@example.com', '3c/144 quan nhân', '695499411181', '2011-03-26', '72 ngõ 49 thúy lĩnh', 'Giám đốc', '63159', 'MBBank', '264/15 Thạnh Lộc 15', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2022-12-01 11:46:18', 'Carter Alcorn', '2023-04-10 10:03:49', 'Admin', NULL),
('156bb711-53c6-12ee-5d80-7ed9d1ea06ea', 'NV-17894', 'Nguyễn Văn Chương', '1958-01-28', 1, '0987419510', '0369989699', 'Malik_Arellano217@nowhere.com', 'B240 ĐHT 11', '112120449430', '2010-01-30', '151 Nguyễn Duy Cung', 'Trường phòng', '83446', 'Sacombank', '73 Kim Hoa', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1974-10-28 19:35:58', 'Elvia Hager', '1984-10-02 19:54:48', 'Valrie Ojeda', NULL),
('15acfdfd-12d7-52f6-2777-d9ebc53aac3d', 'NV-65461', 'Trần Tú Anh', '1953-03-17', 0, '0986369879', '0369878969', 'Lim231@nowhere.com', '301/18A Vườn Lài', '269696800380', '2023-01-03', '308 Quang Trung', 'Trường nhóm', '62707', 'Vietcombank', '67 ngõ 12 bồ đề long biên', '469b3ece-744a-45d5-957d-e8c757976496', '1970-01-01 00:01:16', 'Dante Poindexter', '1971-01-01 00:01:16', 'Angelo Chapa', NULL),
('1737c16a-1277-1be3-3bc2-579daad24557', 'NV-02271', 'Nguyễn Văn Tuấn', '1970-11-19', 0, '0369878969', '0963369896', 'Demetrius_Mcintyre749@example.com', '69/57 Nguyễn Gia Trí', '398192156980', '2010-05-22', '15B/65 Lê Thánh Tôn', 'Giám đốc', '05837', 'ACBank', '413/22 Lê Văn Sỹ', '469b3ece-744a-45d5-957d-e8c757976496', '1995-06-07 05:47:58', 'Joan Dodson', '1971-03-05 12:20:45', 'Amado Hanks', NULL),
('17872e95-3d24-6d1a-32c2-579daad24557', 'NV-79914', 'Trần Ánh Tuyết', '1992-03-28', 1, '0963369896', '0987419510', 'AbigailDunning59@example.com', '33B Phạm Ngũ Lão', '994076358750', '2010-01-09', '101B A3 tập thể Nam Đồng', 'Bảo vệ', '37551', 'VPank', '2/65 Nguyễn Thị Sáu', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2009-10-03 16:28:04', 'Isreal Burk', '1980-03-24 09:47:02', 'Jason Mcnabb', NULL),
('18baaac1-2b18-2317-b9d2-89b22d10517e', 'NV-04010', 'Trương Quang Nhân', '2002-09-15', 0, '0369989699', '0369878963', 'wawwcqng.wmbvidy@example.com', '57/63 tran quoc vượng', '104588901840', '2012-04-01', '186 lê trọng tấn', 'Giám đốc', '57980', 'ACBank', '331/2 Phan Huy Ích', '17120d02-6ab5-3e43-18cb-66948daf6128', '2009-09-24 10:26:59', 'Tim Howe', '2001-09-29 00:43:02', 'Seth Ojeda', NULL),
('18bbd5d8-6c2d-154c-bad2-89b22d10517e', 'NV-68446', 'Nguyễn Việt Thạch', '1988-06-01', 0, '0986369879', '0369889698', 'Shila.Darnell546@example.com', '129 đường số 1', '609253412431', '2014-12-07', '33 Phạm Ngũ Lão', 'Bảo vệ', '61873', 'ACBank', '261 Lê Đức Thọ', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2005-07-25 13:21:13', 'Maria Anthony', '2001-01-27 03:41:08', 'Buford Durden', NULL),
('18d2ec1b-61c5-1896-2ec2-579daad24557', 'NV-69527', 'Nguyễn Văn Phúc', '1962-04-16', 2, '0369877415', '0396398789', 'Marge.Kee32@example.com', '84 Nguyễn Minh Hoàng', '444342567830', '2018-10-23', '33 Phạm Ngũ Lão', 'Trường phòng', '83804', 'Sacombank', 'A25 Đại Từ', '768f8e64-7d10-20c9-967d-e8c757976496', '2004-03-22 02:34:16', 'Debroah Lombard', '2016-01-16 01:13:10', 'Christeen Acker', NULL),
('1906737f-3aed-5704-1777-d9ebc53aac3d', 'NV-75735', 'Trương Văn Khánh', '1957-11-24', 1, '0396398789', '0987419510', 'Cleveland_Hildreth@nowhere.com', '190 Nguyễn Trường Tộ', '880026692480', '2012-04-17', '33B Phạm Ngũ Lão', 'Nhân viên', '85174', 'VPank', '84 Nguyễn Minh Hoàng', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1984-12-22 17:47:54', 'Denita Teal', '1996-08-19 21:00:21', 'Minerva Clifton', NULL),
('19256041-7623-2834-6df6-423b4e874d0f', 'NV-80892', 'Nguyễn Văn Phan', '1971-08-29', 1, '0986369879', '0963369896', 'LindsayMccord@example.com', '38 Đường Tân Thới Hiệp 21', '663105924761', '2017-04-08', '87/117/6 Nguyễn Sỹ Sách', 'Trường phòng', '27235', 'ACBank', '60/15 Vạn Kiếp', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1970-11-11 13:13:38', 'Tasha Gallagher', '1999-04-05 01:12:01', 'Rupert Meyers', NULL),
('192b3b9d-5e60-3b13-5b80-7ed9d1ea06ea', 'NV-45426', 'Nguyễn Vân Huệ', '1954-01-07', 0, '0369878963', '0396398789', 'JeannineAli@example.com', '201/60/12 Nguyễn Xí', '946719361870', '2016-04-16', '326 Nguyễn Trãi', 'Nhân viên', '80363', 'Vietcombank', '27/67 Đức Giang', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1970-01-01 00:06:12', 'Raymundo Alarcon', '1971-01-01 00:06:12', 'Zachariah Toth', NULL),
('197fda97-5a35-781d-0e77-d9ebc53aac3d', 'NV-20804', 'Mai Ngọc Dung', '1979-02-22', 1, '0963369896', '0986369879', 'Almanza@example.com', '110 Nguyễn Đình Chiểu', '366831842871', '2021-06-02', '525 Nguyễn Kiệm', 'Giám đốc', '11427', 'VPank', '33 Phạm Ngũ Lão', '17120d02-6ab5-3e43-18cb-66948daf6128', '1977-09-21 09:30:29', 'Rodrick Paulsen', '2020-09-25 21:55:04', 'Edward Jarvis', NULL),
('1b05fdba-145b-7ab0-8d41-c1ec321fe728', 'NV-52096', 'Trần Trí Thăng', '2001-07-24', 0, '0963369896', '0987419510', 'tsnttoue_pqfyd@example.com', '27 đường số 10', '082241562571', '2017-04-24', '83 hoa bằng', 'Trường phòng', '17888', 'MBBank', '60 Thạnh Lộc 31', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2005-02-06 02:10:01', 'Micah Creighton', '1980-08-17 13:44:09', 'Alesha Landers', NULL),
('1b972dfb-67eb-5f25-39c2-579daad24557', 'NV-54531', 'Trịnh Quang Khương', '1953-07-01', 1, '0976898789', '0369878969', 'RivaStanford@example.com', '2/65 Nguyễn Thị Sáu', '674169441641', '2010-06-29', '43 Đông Hưng Thuận 10B', 'Nhân viên', '71768', 'Vietcombank', '38 Đường Tân Thới Hiệp 21', '768f8e64-7d10-20c9-967d-e8c757976496', '2010-03-18 19:24:02', 'Laine Winston', '1994-10-26 14:34:42', 'Abigail Pratt', NULL),
('1ca4f185-7203-2a84-40c2-579daad24557', 'NV-27132', 'Trịnh Văn Tuệ', '1968-11-16', 1, '0369889698', '0963369896', 'BerylAbraham713@nowhere.com', '33B Phạm Ngũ Lão', '166342156031', '2011-05-22', '483 Phạm Văn Chiêu', 'Trường nhóm', '84832', 'Sacombank', '160 Thạnh Lộc 16', '768f8e64-7d10-20c9-967d-e8c757976496', '2000-08-11 19:30:04', 'Robby Ennis', '1997-02-06 22:52:30', 'Raymon Burdette', NULL),
('1d05a704-5376-15ba-1477-d9ebc53aac3d', 'NV-90451', 'Trịnh Ánh Mai', '1991-11-29', 0, '0369889698', '0369877415', 'Julie_Ackerman45@nowhere.com', 'Số 3 ngõ 13 Lĩnh Nam', '210528358611', '2022-02-05', '656/54 Cách Mạng Tháng 8', 'Bảo vệ', '38225', 'ACBank', 'Tầng 1 nhà Sunrise 3B Khu đô thị Sài Đồng', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2007-07-04 14:37:53', 'Chaya Amador', '1975-07-16 13:05:56', 'Denis Cardwell', NULL),
('1e5ce342-2eec-79a4-5380-7ed9d1ea06ea', 'NV-59626', 'Trần Trọng Phước', '1968-05-11', 1, '0369878969', '0396398789', 'Mario_Bivens@nowhere.com', '41 Thạnh Xuân 52', '821063913351', '2023-02-19', '146 phố Mai Dịch', 'Giám đốc', '40312', 'VPank', '600 Nguyễn Kiệm', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1989-02-27 17:25:55', 'Elliot Paterson', '2011-11-13 13:33:24', 'Roland Clem', NULL),
('1e5e96fa-5d7a-599d-27c2-579daad24557', 'NV-09508', 'Mai Văn Định', '1962-05-18', 2, '0369878963', '0369877415', 'mnksgeiq8021@example.com', '5 Trương Hán Siêu', '749766832260', '2010-03-09', 'số 10/79 tổ 5 yên nghĩa', 'Giám đốc', '67589', 'VPank', '86 đường số 17', '469b3ece-744a-45d5-957d-e8c757976496', '2009-12-29 09:33:28', 'Carline Mccall', '2017-07-21 07:41:22', 'Karly Aguirre', NULL),
('1f85f165-3ed3-370a-b7d2-89b22d10517e', 'NV-94265', 'Trần Văn An', '1981-05-29', 2, '0396398789', '0369877415', 'NorrisBolt@example.com', '003 Lô B, Chung Cư Gò Dầu 2', '474875217181', '2020-01-04', 'kiot 14 HH01C tòa trong KĐT Thanh Hà', 'Trường phòng', '23539', 'Sacombank', '33 Phạm Ngũ Lão', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1979-01-03 15:59:33', 'Kevin Kim', '1984-11-16 11:06:25', 'Vita Morrissey', NULL),
('1f88699a-3e19-718a-d81d-086412a8ea97', 'NV-96009', 'Trần Thị Dương', '1999-11-02', 1, '0369889698', '0369878969', 'Wyatt.Gallegos4@example.com', '47/17 Thăng Long', '898043842900', '2010-03-20', '5 Trương Hán Siêu', 'Trường phòng', '35122', 'Vietcombank', '15/7 Huỳnh Thị Hai', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1990-03-02 22:57:33', 'Chana Talley', '1984-03-24 08:30:10', 'Felix Shoemaker', NULL),
('1fbf8e6f-17d3-6a04-2180-de64d090a2c2', 'NV-44268', 'Nguyễn Thị Liên', '1953-07-11', 1, '0396398789', '0369889698', 'Youngblood@example.com', '21 đường số 2', '082931186900', '2010-02-19', 'Số 4 ngõ 278 Thái Hà', 'Bảo vệ', '59855', 'Sacombank', '95 Tân Thới Nhất 05', '768f8e64-7d10-20c9-967d-e8c757976496', '1998-08-19 15:00:36', 'Latricia Aquino', '1992-10-31 09:02:11', 'Lila Eng', NULL),
('1fecd07f-2488-638c-8141-c1ec321fe728', 'NV-10414', 'Nguyễn Trọng Tuyền', '1956-03-03', 1, '0369989699', '0976898789', 'VellaOlivo14@example.com', '72 ngõ 49 thúy lĩnh', '670989956840', '2013-02-28', '302 Phan Văn Hớn', 'Giám đốc', '09293', 'VPank', '21 đường số 2', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2007-10-14 10:46:12', 'Adolph Braxton', '2021-08-28 21:19:07', 'Cliff Merrick', NULL),
('201b9639-5997-303c-5880-7ed9d1ea06ea', 'NV-71904', 'Nguyễn Ngọc Nhài', '1984-10-17', 2, '0976898789', '0369878963', 'LeonStafford295@example.com', '35B đường 494', '566489064961', '2017-08-03', '30 đường số 9', 'Nhân viên', '92261', 'VPank', '638 Tỉnh Lộ 10', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1997-05-25 03:49:44', 'Sanda Colvin', '1988-07-01 01:35:11', 'Josue Mcdonnell', NULL),
('2107e2a5-49f8-237b-5780-7ed9d1ea06ea', 'NV-89675', 'Hoàng Hưng Dương', '1957-02-23', 0, '0396398789', '0976898789', 'kcrx1294@nowhere.com', '2808/3B Khu Phố 3', '780295728661', '2022-01-26', '288 Cách Mạng Tháng 8', 'Bảo vệ', '54910', 'VPank', '525 Phúc Diễn', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1976-12-31 08:53:56', 'Clay Pinkston', '1986-08-23 09:38:39', 'Alvin Jay', NULL),
('212a5f62-4eb8-203c-4035-0028ed526dd0', 'NV-09573', 'Nguyễn Văn Danh', '1987-05-16', 0, '0369878969', '0987419510', 'kwmfds89@example.com', '48/299 Hoàng Mai', '912262649911', '2010-02-17', '108D8 Nguyên Hồng', 'Bảo vệ', '10569', 'MBBank', '152 ngõ 171 Nguyễn Xiển', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1973-03-30 18:01:35', 'Columbus Ackerman', '2014-05-06 09:25:28', 'Alexis Fagan', NULL),
('21ae5078-5e68-3790-6af6-423b4e874d0f', 'NV-30383', 'Trần Văn Thạch', '1953-01-12', 1, '0369989699', '0369889698', 'ErasmoA_Armenta@nowhere.com', 'Số 179 khu dịch vụ Xa La', '164895621180', '2022-09-09', '104A Tân Chánh Hiệp 10', 'Bảo vệ', '86674', 'ACBank', '3/54A Thạnh Lộc 29', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1970-01-01 00:00:12', 'Annemarie Hammer', '1971-01-01 00:00:12', 'Otis Calkins', NULL),
('22732821-2015-1da3-4335-0028ed526dd0', 'NV-17653', 'Mai Văn An', '2002-08-23', 0, '0369889698', '0963369896', 'Chana.Siegel@example.com', '149 ngõ 670 nguyễn khoái', '572292590641', '2010-10-22', '35B đường 494', 'Bảo vệ', '48922', 'ACBank', '58 Trần Hưng Đạo', '768f8e64-7d10-20c9-967d-e8c757976496', '1986-04-03 16:28:46', 'Waltraud Abbott', '2010-08-24 10:01:04', 'Donald Thibodeau', NULL),
('22bba567-6206-6bf1-0c35-60b3ebf808a9', 'NV-11866', 'Nguyễn Thị Nga', '1960-08-30', 0, '0369889698', '0369878969', 'Adcock@nowhere.com', 'E39 Khu Đấu Giá Ngô Thì Nhậm', '740553434820', '2014-05-28', '33 Phạm Ngũ Lão', 'Giám đốc', '58978', 'VPank', '33B Phạm Ngũ Lão', '469b3ece-744a-45d5-957d-e8c757976496', '1977-01-13 04:59:12', 'Willis Thomas', '2002-07-26 22:12:35', 'Dexter Angulo', NULL),
('22df58b0-55d2-6108-2480-de64d090a2c2', 'NV-65517', 'Nguyễn Ánh Thoa', '1968-10-25', 2, '0369878963', '0986369879', 'CarolLilley@example.com', '982 quốc lộ 1A', '865955234520', '2012-12-07', 'Kiot 1 Chợ Yên Phúc', 'Bảo vệ', '39722', 'ACBank', '248/16 Nguyễn Thái Bình', '17120d02-6ab5-3e43-18cb-66948daf6128', '1970-01-01 01:36:17', 'Birgit Salisbury', '1971-01-01 01:36:17', 'Ernestina Witte', NULL),
('22f0091b-523a-6c8e-4c35-0028ed526dd0', 'NV-07432', 'Đinh Thành Thạch', '1979-06-24', 2, '0369878969', '0369878969', 'Petrie@example.com', '37/72 dịch vọng', '716100046411', '2010-08-12', '39/65 mai dịch', 'Bảo vệ', '36303', 'Vietcombank', '149 ngõ 670 nguyễn khoái', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1970-01-01 02:41:11', 'Loren Dennison', '1971-01-01 02:41:11', 'Erich Burger', NULL),
('233d36ab-4bd0-431e-78f6-423b4e874d0f', 'NV-14455', 'Võ Văn Nam', '1974-09-17', 1, '0987419510', '0987419510', 'Carmine_ZPeoples@example.com', '6D6 khu giãn dân yên phúc', '888063655280', '2011-08-20', '33 Phạm Ngũ Lão', 'Giám đốc', '74449', 'Vietcombank', '47 Trần Quốc Toản', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1998-11-20 18:28:42', 'Daniel Churchill', '2006-04-01 15:36:30', 'Alden Hackett', NULL),
('234865cb-5d80-7244-70f6-423b4e874d0f', 'NV-79226', 'Bùi Khánh Dung', '1953-02-10', 0, '0369878969', '0963369896', 'May@nowhere.com', 'kiot 6 chợ Yên Phúc', '717877482170', '2010-02-12', '02- Lô F003 CC Sơn Kỳ 1', 'Trường phòng', '09392', 'Vietcombank', 'Kiot 23+24 Chợ Yên Phúc', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1970-01-01 00:00:41', 'Breana Frey', '1971-01-01 00:00:41', 'Emil Sumner', NULL),
('2356a2d8-7751-6f97-66f6-423b4e874d0f', 'NV-40709', 'Nguyễn Văn Thăng', '1965-04-06', 2, '0976898789', '0369877415', 'Dodge@example.com', '302/78A Phan Huy Ích', '840290791021', '2016-07-22', '23 ngõ 26 tư đình', 'Trường nhóm', '92568', 'Sacombank', '108D8 Nguyên Hồng', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2018-07-31 20:30:44', 'Akiko Lester', '1974-06-20 23:53:19', 'Kristle Dickens', NULL),
('237092c3-5684-7bb6-0a35-60b3ebf808a9', 'NV-73091', 'Trương Thị Thanh', '2002-04-09', 0, '0976898789', '0976898789', 'Rodriguez@example.com', '106 Nguyễn Thị Sáu', '268593622271', '2010-03-02', '23 ngõ 26 tư đình', 'Trường nhóm', '08047', 'Sacombank', '11/67 Thái Thịnh', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2012-05-15 12:57:03', 'Rosette Means', '2016-03-31 11:56:54', 'Adriene Freund', NULL),
('244b1b16-56fc-1f92-73f6-423b4e874d0f', 'NV-47771', 'Nguyễn Thị Hương', '1965-05-07', 0, '0369878969', '0976898789', 'AndyAmmons@example.com', '45 đường số 3', '406081955071', '2021-05-02', '205 Lê Văn Chí', 'Giám đốc', '97473', 'VPank', '165 đường 339', '17120d02-6ab5-3e43-18cb-66948daf6128', '1973-04-17 09:47:33', 'Beverly Shepherd', '1985-05-26 20:08:38', 'Toshia Hanley', NULL),
('255b28ba-2177-6baf-0835-60b3ebf808a9', 'NV-40219', 'Trương Văn Triệu', '1973-06-17', 0, '0369878963', '0987419510', 'Costello536@example.com', '525 Nguyễn Kiệm', '174893151041', '2010-01-24', '467 Vĩnh Hưng', 'Nhân viên', '81601', 'VPank', 'E39 Khu Đấu Giá Ngô Thì Nhậm', '768f8e64-7d10-20c9-967d-e8c757976496', '2004-11-13 14:20:54', 'Javier Daley', '2015-08-06 06:17:10', 'Adela Winchester', NULL),
('26942456-25a8-5ec2-8b41-c1ec321fe728', 'NV-78601', 'Nguyễn Thị Mai', '1981-10-14', 2, '0987419510', '0963369896', 'Abrams42@nowhere.com', '5 Quang Trung', '906932168841', '2013-12-28', '638 Tỉnh Lộ 10', 'Giám đốc', '61049', 'VPank', '331/2 Phan Huy Ích', '768f8e64-7d10-20c9-967d-e8c757976496', '1980-02-17 00:49:02', 'Mae Abraham', '1972-10-02 00:58:55', 'Dorthea Keith', NULL),
('27e60da2-385e-6804-8441-c1ec321fe728', 'NV-01418', 'Nguyễn Thị Băng', '1976-08-18', 0, '0976898789', '0369877415', 'KingCarter@example.com', '31/250 kim giang', '032421535250', '2010-01-14', '35B đường 494', 'Giám đốc', '02623', 'MBBank', '118 đường 26/3', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2005-09-24 05:52:33', 'Alonzo Agee', '2015-12-09 17:40:15', 'Gilberto Wallis', NULL),
('2872c174-68d3-29c1-4935-0028ed526dd0', 'NV-04502', 'Trần Văn Tuấn', '1954-10-05', 1, '0976898789', '0987419510', 'Dayton@example.com', 'Kiot 1 Chợ Yên Phúc', '691724315241', '2010-09-22', '95/33 Lê Tấn Bê', 'Bảo vệ', '33160', 'MBBank', '73 Kim Hoa', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1970-01-01 00:10:43', 'Isadora Beckham', '1971-01-01 00:10:43', 'Dominga Abernathy', NULL),
('28a16581-1fd1-546b-1677-d9ebc53aac3d', 'NV-27471', 'Nguyễn Thị Ly', '1984-09-06', 1, '0369889698', '0963369896', 'GreggGaskin@example.com', '43 Đông Hưng Thuận 10B', '908823659250', '2010-01-09', '207/51 Hồ Học Lãm', 'Trường nhóm', '43288', 'MBBank', '36 Phan Đình Giót', '17120d02-6ab5-3e43-18cb-66948daf6128', '1991-05-21 10:42:19', 'Myrl Combs', '1974-10-21 05:15:49', 'Adela Haggard', NULL),
('28cd1599-63bf-785f-4f80-7ed9d1ea06ea', 'NV-47975', 'Nguyễn Ánh Hồng', '1983-05-05', 0, '0396398789', '0986369879', 'Ron.Irish@example.com', '21 đường số 2', '494376930771', '2022-08-29', '146 Phạm Văn Chiêu', 'Trường phòng', '27438', 'Sacombank', '118 Đông Hưng Thuận 06', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1995-10-06 08:27:41', 'Marco Horn', '1975-01-31 12:05:58', 'Wesley Ramirez', NULL),
('2afb2146-430d-394b-3d35-0028ed526dd0', 'NV-37107', 'Nông Thành Triệu', '1982-10-21', 0, '0976898789', '0369878969', 'AntoineLittlefield@nowhere.com', '201/60/12 Nguyễn Xí', '940034702551', '2012-01-25', '369 Bà Hạt', 'Nhân viên', '65154', 'Sacombank', '860/56 Xô Viết Nghệ Tĩnh', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1999-05-26 19:36:49', 'Minh Withers', '1995-12-23 03:13:39', 'Neal Bergman', NULL),
('2bd927cf-7faf-452e-4535-0028ed526dd0', 'NV-70542', 'Mai Kim Bình', '1960-06-30', 2, '0369878969', '0976898789', 'AudreyVoss@example.com', 'B240 ĐHT 11', '170272154871', '2015-02-24', '21A Lô Tư', 'Trường nhóm', '46428', 'VPank', '302/78A Phan Huy Ích', '768f8e64-7d10-20c9-967d-e8c757976496', '1992-12-06 14:22:34', 'Chiquita Downs', '1997-10-16 06:03:49', 'Ammie Mcnally', NULL),
('2c06d3cb-7ef7-4462-5e80-7ed9d1ea06ea', 'NV-10137', 'Hồ Ánh Hà', '1953-08-23', 1, '0369878969', '0369878963', 'bsmbmevr.huhr@example.com', '27/67 Đức Giang', '365327800120', '2022-01-17', '483 Phạm Văn Chiêu', 'Trường nhóm', '43491', 'VPank', '146 Phạm Văn Chiêu', '17120d02-6ab5-3e43-18cb-66948daf6128', '1970-01-01 00:03:55', 'Nita Mcwhorter', '1971-01-01 00:03:55', 'Alison Long', NULL),
('2c380a42-1611-28c2-3ac2-579daad24557', 'NV-05282', 'Trương Văn Chính', '1963-05-21', 1, '0987419510', '0369878963', 'wkjvspno405@nowhere.com', '21 Ngũ Nhạc', '405354900380', '2015-08-01', '12 phan bá vành', 'Nhân viên', '98494', 'MBBank', '84A Tôn Thất Hiệp', '768f8e64-7d10-20c9-967d-e8c757976496', '1990-12-09 07:03:30', 'Elton Strauss', '2015-06-11 03:42:16', 'Carmine Chung', NULL),
('2efc0ff3-37c0-286f-bbd2-89b22d10517e', 'NV-77937', 'Nguyễn Minh Long', '1980-08-15', 0, '0369989699', '0396398789', 'ErnestBelanger@nowhere.com', '12 phan bá vành', '566112165141', '2020-12-20', '11/67 Thái Thịnh', 'Bảo vệ', '88178', 'VPank', '27/67 Đức Giang', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2016-09-16 10:00:10', 'Adeline Levesque', '1992-03-23 18:13:58', 'Shaunda Escalante', NULL),
('2f43fc9d-1f7a-25fc-5280-7ed9d1ea06ea', 'NV-70012', 'Trịnh Khánh Hương', '1954-07-05', 1, '0976898789', '0963369896', 'Chasidy.Nye82@example.com', '2/1/481 Ngọc Lâm', '577944340431', '2010-10-22', '47 Trần Quốc Toản', 'Bảo vệ', '73086', 'Sacombank', '173 Văn Chương', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2023-02-11 09:35:39', 'Marylyn Medina', '1972-12-05 05:09:07', 'Jamika Mendez', NULL),
('2f4cc91d-6f13-4b4c-1c80-de64d090a2c2', 'NV-75821', 'Trần Văn Tuân', '1955-08-03', 2, '0396398789', '0369889698', 'Abel_Stratton@example.com', '165 đường 339', '950825025481', '2018-09-27', '118 Đông Hưng Thuận 06', 'Giám đốc', '76550', 'ACBank', '60/15 Vạn Kiếp', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1970-01-01 00:15:45', 'Teena Mintz', '1971-01-01 00:15:45', 'Laurette Larose', NULL),
('2fde0921-432c-64c5-0935-60b3ebf808a9', 'NV-52458', 'Nông Thành An', '1966-10-08', 2, '0369889698', '0963369896', 'Laurence_Tiller173@example.com', '16/49 Trần Cung', '984856814381', '2016-07-09', '213 Trần Cung', 'Trường phòng', '50058', 'Vietcombank', '102 lạc long quân', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2006-11-17 10:07:10', 'Andy Tennant', '2019-11-20 05:00:46', 'Walker Alba', NULL),
('31ae1818-7baf-1872-1e77-d9ebc53aac3d', 'NV-11176', 'Trần Thị Bình', '1953-01-01', 0, '0369878969', '0976898789', 'Ela_Renteria444@nowhere.com', '288 Cách Mạng Tháng 8', '823182832671', '2022-07-29', '697 Vũ Tông Phan', 'Nhân viên', '09059', 'VPank', '114/14 Tô Ngọc Vân', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1970-01-01 00:00:01', 'Penny Abrams', '1971-01-01 00:00:01', 'Darwin Staples', NULL),
('322105dd-142f-392d-2fc2-579daad24557', 'NV-02395', 'Nguyễn Hưng Mạnh', '1967-01-06', 0, '0369889698', '0986369879', 'Alec.Trejo21@nowhere.com', 'Kiot 23+24 Chợ Yên Phúc', '075855095290', '2018-04-13', '11/15 Lương Định Của', 'Trường nhóm', '71372', 'Sacombank', 'kiot 6 chợ Yên Phúc', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2001-06-16 11:30:20', 'Tawny Lister', '2011-12-15 19:59:32', 'Rueben Viera', NULL),
('324ac33a-77c5-13a5-0535-60b3ebf808a9', 'NV-17940', 'Trịnh Thị Huệ', '1953-01-18', 0, '0976898789', '0963369896', 'Noe_Damico@example.com', '213 Trần Cung', '575535694371', '2013-08-08', '15/15A25', 'Nhân viên', '42794', 'Vietcombank', '273 tổ 4', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1970-01-01 00:00:18', 'Donovan Buckley', '1971-01-01 00:00:18', 'Abel Self', NULL),
('329b5332-34e3-1ae4-6ef6-423b4e874d0f', 'NV-61288', 'Nguyễn Văn Xuân', '1979-04-08', 1, '0369989699', '0369877415', 'PamulaD.Sena@example.com', 'No07 liền kề 222 khu cây quýt Văn Khê', '819963952690', '2020-11-06', '157B Đường TX 21', 'Trường phòng', '68773', 'ACBank', '12 phan bá vành', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2007-06-30 01:55:03', 'Jerrold Berg', '1980-09-17 22:05:12', 'Dulce Kellogg', NULL),
('32d33559-61a5-4afd-d91d-086412a8ea97', 'NV-77168', 'Đinh Văn Tuyền', '1960-04-30', 1, '0976898789', '0369989699', 'gczp6186@example.com', '66 Trần Minh Quyền', '528759513260', '2016-04-13', '36 Thạch Yên', 'Nhân viên', '22338', 'Vietcombank', 'Số 2 ngõ 2 nhân hoà', '17120d02-6ab5-3e43-18cb-66948daf6128', '1971-07-07 09:59:05', 'Dwayne Allen', '1995-11-05 11:08:14', 'Mohamed Abel', NULL),
('3304dddb-1b72-607f-25c2-579daad24557', 'NV-06388', 'Trần Anh Nguyên', '1958-03-07', 1, '0369889698', '0369878963', 'Conrad_Frizzell61@example.com', '27/67 Đức Giang', '674076485021', '2011-03-13', '114/14 Tô Ngọc Vân', 'Nhân viên', '96821', 'MBBank', 'Số 179 khu dịch vụ Xa La', '469b3ece-744a-45d5-957d-e8c757976496', '2017-03-10 03:04:12', 'Vanita Edmonds', '2010-03-28 16:42:07', 'Scot Acker', NULL),
('330c9d97-d74b-11ed-8de1-d8d09038d020', 'NV-99449', 'Phạm Hoàng Thắng', '1970-05-19', 2, '0963369896', '0369878969', 'Mckinley_Barbosa835@nowhere.com', '3c/144 quan nhân', '608336103771', '2010-01-31', 'số 3 Phùng Khoang', 'Trường phòng', '33606', 'Vietcombank', '239 Tân Thới Nhất', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2023-04-10 09:55:49', '', '2023-04-10 09:55:49', '', NULL),
('337faf61-662b-461a-69f6-423b4e874d0f', 'NV-50827', 'Nguyễn Thị Đan', '1953-02-16', 0, '0369878969', '0369878969', 'Manson@example.com', '36 Phan Đình Giót', '717883357600', '2016-02-03', '5 Quang Trung', 'Nhân viên', '61127', 'MBBank', '75/14 An Phú Đông 9', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1970-01-01 00:00:47', 'Adela Chan', '1971-01-01 00:00:47', 'Delmy Peeler', NULL),
('33ec4fea-4c03-3191-3ec2-579daad24557', 'NV-28146', 'Nguyễn Văn Chiến', '2000-02-24', 1, '0369878963', '0976898789', 'dxrgd2632@nowhere.com', '201/60/12 Nguyễn Xí', '551764691241', '2010-01-14', '212/204 Nguyễn Văn Nguyễn', 'Trường phòng', '03224', 'VPank', '12 phan bá vành', '768f8e64-7d10-20c9-967d-e8c757976496', '2017-12-30 19:44:23', 'Duane Abernathy', '2022-05-23 18:34:52', 'Isaias Keeton', NULL),
('34d0e3b5-6d5f-1fd7-0635-60b3ebf808a9', 'NV-12433', 'Vũ Văn Công', '1953-02-24', 0, '0986369879', '0963369896', 'LukeLaplante@example.com', '52 Võ Thị Thừa', '389876380211', '2011-06-11', '5 Trương Hán Siêu', 'Bảo vệ', '64481', 'MBBank', '264/15 Thạnh Lộc 15', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1970-01-01 00:00:55', 'Aleta Abraham', '1971-01-01 00:00:55', 'Devon Coleman', NULL),
('350cf027-3245-532d-bcd2-89b22d10517e', 'NV-04733', 'Hồ Hưng Kiên', '1958-04-01', 0, '0396398789', '0369878969', 'tegaafuz6022@example.com', '3/54A Thạnh Lộc 29', '649895608620', '2012-08-04', 'kiot 6 chợ Yên Phúc', 'Trường phòng', '95506', 'ACBank', '50/13 Thạnh Xuân 25', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2011-01-23 22:31:59', 'Hung Ackerman', '1987-08-11 16:19:17', 'August Solano', NULL),
('35c3a053-254d-33f3-1b80-de64d090a2c2', 'NV-13295', 'Nguyễn Anh Phúc', '1955-06-16', 0, '0396398789', '0396398789', 'Acker@example.com', '149b/e Tô Ngọc Vân', '814282457401', '2021-07-10', '15/7 Huỳnh Thị Hai', 'Trường phòng', '69351', 'VPank', '5 Quang Trung', '17120d02-6ab5-3e43-18cb-66948daf6128', '1970-01-01 00:14:57', 'Adam Thames', '1971-01-01 00:14:57', 'Joye Ryder', NULL),
('35ec2e7b-17b3-1b63-6080-7ed9d1ea06ea', 'NV-37518', 'Trần Trí Bình', '1953-02-26', 1, '0369878969', '0369889698', 'Santa.Ammons@nowhere.com', '301/18A Vườn Lài', '103353262661', '2021-08-29', '5/6A Song Hành', 'Giám đốc', '94714', 'ACBank', '288 Cách Mạng Tháng 8', '17120d02-6ab5-3e43-18cb-66948daf6128', '1970-01-01 00:00:57', 'Franklin Aiello', '1971-01-01 00:00:57', 'Timothy Pierson', NULL),
('360bd1e4-7bbf-3971-d41d-086412a8ea97', 'NV-93082', 'Nguyễn Thị Hà', '1973-07-14', 1, '0369889698', '0986369879', 'RomeoDorris17@example.com', '697 Vũ Tông Phan', '148154861370', '2010-03-09', '31/250 kim giang', 'Trường nhóm', '21982', 'Sacombank', 'Kiot 22 – HH03D, khu đô thị Thanh Hà', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1978-06-24 11:03:01', 'Janell Beale', '1984-08-18 07:53:28', 'Abdul Halsey', NULL),
('36ac2df8-2b1e-368f-cc1d-086412a8ea97', 'NV-43551', 'Hồ Văn Tuấn', '1988-08-25', 2, '0369889698', '0369878969', 'Atwood@nowhere.com', 'Số 2 ngõ 2 nhân hoà', '252817592921', '2013-11-11', '33 Phạm Ngũ Lão', 'Trường phòng', '60676', 'Vietcombank', '207/21 Hồ Học Lãm', '768f8e64-7d10-20c9-967d-e8c757976496', '2008-11-16 01:24:46', 'Cora Pacheco', '2015-09-16 20:04:57', 'Rueben Sell', NULL),
('3738ce93-1661-5628-2cc2-579daad24557', 'NV-61482', 'Đinh Thị Liên', '1996-03-04', 0, '0396398789', '0369889698', 'pqjndav80@example.com', '2M16 -104 Nguyễn An Ninh', '589571348270', '2022-06-15', '21 đường số 2', 'Bảo vệ', '83937', 'Sacombank', 'số 3 ngách 10 ngõ 122 phố vĩnh tuy', '17120d02-6ab5-3e43-18cb-66948daf6128', '1976-09-10 04:23:01', 'Louie Freedman', '1997-02-09 05:02:52', 'Rolande Price', NULL),
('383760d5-6851-218b-4835-0028ed526dd0', 'NV-09903', 'Trần Thị Phượng', '1986-12-21', 0, '0369889698', '0963369896', 'DenverSewell899@example.com', '128/6 Phạm Văn Hai', '946536047170', '2022-08-20', '187 đường số 1', 'Trường nhóm', '90562', 'ACBank', '328 Lê Văn Việt', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2018-04-26 00:56:06', 'Abel Conn', '2019-12-03 20:52:47', 'Shenna Hildebrand', NULL),
('38dc720e-654a-29d5-34c2-579daad24557', 'NV-54583', 'Trịnh Thị Dương', '1982-08-01', 2, '0976898789', '0369878969', 'Adam.Runyan27@example.com', '467 Vĩnh Hưng', '010123515830', '2020-01-07', '288 Cách Mạng Tháng 8', 'Trường nhóm', '15911', 'Vietcombank', '58 Trần Hưng Đạo', '768f8e64-7d10-20c9-967d-e8c757976496', '2001-06-23 17:50:55', 'Deandra Acevedo', '1972-11-08 13:14:07', 'Oscar Mayo', NULL),
('395826c8-15a0-31f9-5980-7ed9d1ea06ea', 'NV-64741', 'Trịnh Văn Chính', '1998-03-21', 0, '0396398789', '0369878969', 'Baughman@nowhere.com', '27/67 Đức Giang', '007694196291', '2016-07-16', 'R28 Dương Thị Giang', 'Trường nhóm', '59119', 'Sacombank', '212/204 Nguyễn Văn Nguyễn', '469b3ece-744a-45d5-957d-e8c757976496', '1991-08-09 17:50:00', 'Kena Edward', '2006-09-05 04:08:44', 'Broderick Aviles', NULL),
('395fb299-3c5f-46fe-8841-c1ec321fe728', 'NV-80389', 'Nguyễn Thị Châu', '1963-12-10', 0, '0369877415', '0369889698', 'CortezAlderman@example.com', '525 Nguyễn Kiệm', '039097496071', '2010-07-04', '211 Giáp Bát', 'Bảo vệ', '35387', 'ACBank', '177 ngõ 467 lĩnh nam', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1992-05-23 20:29:03', 'Velma Hackney', '1978-04-15 13:58:35', 'Porter Beltran', NULL),
('3a425a4d-6066-116b-6bf6-423b4e874d0f', 'NV-97162', 'Nguyễn Văn Dương', '1977-09-15', 1, '0369877415', '0369878963', 'Baron964@nowhere.com', '697 Vũ Tông Phan', '264740608011', '2016-12-12', '12 phan bá vành', 'Trường phòng', '16827', 'VPank', '41 Thạnh Xuân 52', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2014-08-09 00:46:52', 'Delorse Mayes', '1996-06-11 20:59:12', 'Adam Mccarty', NULL),
('3abffc51-2a43-18c6-6cf6-423b4e874d0f', 'NV-49223', 'Nguyễn Ngọc Nghĩa', '1953-01-10', 2, '0986369879', '0369878969', 'GalenPino@example.com', '38 đường số 8', '000435998340', '2018-12-25', '213 Trần Cung', 'Bảo vệ', '72914', 'ACBank', '33B Phạm Ngũ Lão', '469b3ece-744a-45d5-957d-e8c757976496', '1970-01-01 00:00:10', 'Eugene Valadez', '1971-01-01 00:00:10', 'Tod Abbott', NULL),
('3b668e3c-742f-4876-8e41-c1ec321fe728', 'NV-31658', 'Nguyễn Mỹ Loan', '1957-06-05', 1, '0987419510', '0369878963', 'DouglasSisson9@example.com', '982 quốc lộ 1A', '822120523860', '2010-08-28', '118 đường 26/3', 'Giám đốc', '89544', 'ACBank', '331/2 Phan Huy Ích', '469b3ece-744a-45d5-957d-e8c757976496', '2004-06-23 02:01:14', 'Graham Faulkner', '2011-01-04 16:52:53', 'Concha Rauch', NULL),
('3b9ddf67-2552-6683-5a80-7ed9d1ea06ea', 'NV-27690', 'Trần Trí Anh', '1956-03-12', 0, '0369989699', '0396398789', 'xtjlpw4@example.com', '369 Bà Hạt', '282848716260', '2015-01-15', '86 đường số 17', 'Trường phòng', '16483', 'Vietcombank', '165 đường 339', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2017-10-18 20:56:29', 'Idalia Moye', '1986-12-03 13:24:46', 'Otis Easton', NULL),
('3cb58bb5-2fd7-6c15-8741-c1ec321fe728', 'NV-07368', 'Mai Thị Mỹ', '1990-11-13', 2, '0369989699', '0976898789', 'AdelaK_Clawson322@example.com', '102 lạc long quân', '439509459791', '2022-11-22', '92/28 Vườn Lài', 'Bảo vệ', '24301', 'Sacombank', '567/66 Lê Văn Khương', '17120d02-6ab5-3e43-18cb-66948daf6128', '2020-12-27 17:37:44', 'Irving Lusk', '2012-04-29 02:21:34', 'Rudy Calvert', NULL),
('3cc7be2d-6406-4b95-3cc2-579daad24557', 'NV-85055', 'Nông Thị Hà', '1994-03-09', 2, '0986369879', '0369877415', 'Angie_Chu6@example.com', '240E Tô Ngọc Vân', '942420778340', '2010-02-10', '31/250 kim giang', 'Trường phòng', '27852', 'Vietcombank', '39/65 mai dịch', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1999-07-25 17:47:04', 'Truman Aiken', '2006-09-19 06:41:21', 'Laila Short', NULL),
('3d1266d8-49d7-3605-2477-d9ebc53aac3d', 'NV-81534', 'Nguyễn Anh Nguyên', '1976-05-05', 2, '0963369896', '0369878969', 'Darron_Roberson@example.com', '72 ngõ 49 thúy lĩnh', '515758754641', '2010-04-03', '102 đường 26/3', 'Trường phòng', '07684', 'Vietcombank', '261 Lê Đức Thọ', '17120d02-6ab5-3e43-18cb-66948daf6128', '2016-02-26 17:56:14', 'Marci Acker', '1982-11-01 14:49:33', 'Jeffery Lynch', NULL),
('3d18d4c2-2f39-3dce-d61d-086412a8ea97', 'NV-75856', 'Hoàng Thị Bích', '1966-12-28', 1, '0369889698', '0369989699', 'zjnogqkv_umtich@example.com', '102 đường 26/3', '054810232631', '2010-06-01', 'Số 2 ngõ 2 nhân hoà', 'Nhân viên', '84305', 'Sacombank', '25 Ngõ 2 Đại Từ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2014-06-06 07:10:14', 'Hwa Beckman', '2016-01-16 06:33:35', 'Adelina Browne', NULL),
('3e51a46c-4153-229c-7f41-c1ec321fe728', 'NV-94481', 'Trần Hưng Chính', '1976-07-27', 1, '0396398789', '0369877415', 'Abel313@example.com', '003 Lô B, Chung Cư Gò Dầu 2', '233808653431', '2019-12-01', '15/7 Huỳnh Thị Hai', 'Bảo vệ', '48851', 'VPank', '151 Nguyễn Duy Cung', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1981-07-27 02:05:01', 'Olga Haag', '1989-09-09 21:12:47', 'Romeo Anderson', NULL),
('3e7dd0ec-7ee5-392a-1277-d9ebc53aac3d', 'NV-36357', 'Trần Văn Thanh', '1972-03-10', 1, '0976898789', '0987419510', 'JerroldSAkins@example.com', '84 Nguyễn Minh Hoàng', '819880352820', '2016-09-15', '83 hoa bằng', 'Bảo vệ', '03179', 'ACBank', '860/56 Xô Viết Nghệ Tĩnh', '469b3ece-744a-45d5-957d-e8c757976496', '1985-04-21 12:24:49', 'Everette Anders', '1994-12-23 18:38:35', 'Kyung Andrew', NULL),
('3f7028bf-3771-75c5-2380-de64d090a2c2', 'NV-31629', 'Trần Thị Thu', '1953-01-01', 2, '0396398789', '0369878969', 'MinhWord@nowhere.com', '60/15 Vạn Kiếp', '100118385130', '2013-02-14', '165 đường 339', 'Trường nhóm', '83646', 'Sacombank', '11/15 Lương Định Của', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1970-01-01 00:00:01', 'Randy Ackerman', '1971-01-01 00:00:01', 'Lang Guillory', NULL),
('3fc4ed08-1219-1c6d-5480-7ed9d1ea06ea', 'NV-61408', 'Bùi Việt Triệu', '1975-04-07', 0, '0369878963', '0369889698', 'DeanaAgee@example.com', '15/15A25', '723572243620', '2013-10-21', '118 đường 26/3', 'Trường nhóm', '00072', 'Vietcombank', '227 Đường Số 1', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2006-09-03 08:59:25', 'Michel Beale', '1972-06-15 06:49:52', 'Barb Egan', NULL),
('3fed64ec-2f94-798f-0335-60b3ebf808a9', 'NV-82476', 'Nguyễn Thị Duyên', '1995-06-22', 2, '0369878963', '0369878963', 'Joseph.Trapp@example.com', '104A Tân Chánh Hiệp 10', '662682135911', '2023-01-27', '77/337 dịch vọng', 'Trường nhóm', '97695', 'Sacombank', '2M16 -104 Nguyễn An Ninh', '768f8e64-7d10-20c9-967d-e8c757976496', '2000-08-12 23:11:49', 'Hilma Bower', '1980-06-30 14:15:04', 'Gabriela Harmon', NULL),
('4029deb6-568c-284f-8941-c1ec321fe728', 'NV-65509', 'Bùi Thị Huyền', '1953-04-23', 2, '0369878969', '0369889698', 'Alvarez39@example.com', '71 Thạnh Lộc 16', '372165790611', '2010-01-08', '38 đường số 8', 'Trường nhóm', '89926', 'MBBank', '49 Nguyễn Trung Ngạn', '469b3ece-744a-45d5-957d-e8c757976496', '2020-01-21 18:02:23', 'Suzann Barry', '2002-08-27 18:25:21', 'Raleigh Connelly', NULL),
('405d596c-21be-7e1a-3dc2-579daad24557', 'NV-13587', 'Nguyễn Kim Hà', '1962-08-02', 1, '0396398789', '0987419510', 'Aguirre2@example.com', 'Số 8 Tân Thới Nhất 12', '567399092901', '2015-12-23', '104A Tân Chánh Hiệp 10', 'Giám đốc', '91630', 'Vietcombank', '525 Phúc Diễn', '768f8e64-7d10-20c9-967d-e8c757976496', '1970-01-01 00:58:21', 'Adam Cousins', '1971-01-01 00:58:21', 'Matthew Harbin', NULL),
('407db4d1-222b-287d-0135-60b3ebf808a9', 'NV-24089', 'Trương Thị Hường', '1982-01-17', 1, '0369878963', '0963369896', 'JeraldAbraham529@example.com', '17 Y Sơn 2', '458744493341', '2011-08-12', '239 Tân Thới Nhất', 'Trường phòng', '22638', 'MBBank', '003 Lô B, Chung Cư Gò Dầu 2', '17120d02-6ab5-3e43-18cb-66948daf6128', '1986-02-23 01:22:24', 'Nerissa Word', '2017-11-22 14:30:12', 'Christian Gill', NULL),
('409dcd1a-426a-23f7-3a35-0028ed526dd0', 'NV-15652', 'Nguyễn Khánh Trà', '2000-07-21', 1, '0369889698', '0369889698', 'Kirk.HKoehler@nowhere.com', '07 Hoàng Hữu Nam', '094150970421', '2010-01-09', '187 đường số 1', 'Giám đốc', '75243', 'VPank', '135 Hồ Văn Tư', '768f8e64-7d10-20c9-967d-e8c757976496', '1995-01-10 11:55:13', 'Gus Sawyer', '1992-03-27 05:52:26', 'Almeta Bowling', NULL),
('417f31fa-5c7b-6b08-6280-7ed9d1ea06ea', 'NV-09195', 'Hoàng Văn Tuấn', '1998-04-01', 1, '0369878969', '0396398789', 'AikoMartz@nowhere.com', 'Số 3 ngõ 13 Lĩnh Nam', '531790216880', '2010-03-29', '129 đường số 1', 'Bảo vệ', '93704', 'Sacombank', '102 đường 26/3', '469b3ece-744a-45d5-957d-e8c757976496', '1987-10-07 14:19:37', 'John Bello', '2014-06-12 17:29:38', 'Shirl Abreu', NULL),
('41f1acba-3177-4b1c-c4d2-89b22d10517e', 'NV-57776', 'Nguyễn Minh Triệu', '1988-02-15', 1, '0369889698', '0369878963', 'ArmindaBurkett986@example.com', '213 Trần Cung', '261591272980', '2011-09-29', '58 Lâm Thị Hố', 'Nhân viên', '58692', 'Sacombank', 'Ki ốt 4 -19t6 khu đô thị Kiến Hưng', '469b3ece-744a-45d5-957d-e8c757976496', '1983-09-26 12:23:21', 'Ailene Akin', '2001-09-30 04:47:03', 'Ricardo East', NULL),
('42a13e31-2abb-6171-dc1d-086412a8ea97', 'NV-48790', 'Nguyễn Thị Thanh', '1968-02-14', 1, '0369877415', '0369889698', 'upcvcla96@nowhere.com', '21 Ngũ Nhạc', '717140561771', '2010-06-17', '21 Ngũ Nhạc', 'Nhân viên', '26200', 'Sacombank', 'Ki ốt6 ct4a kđt xa la', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1970-12-10 08:12:59', 'Romana Blanco', '1973-10-21 23:08:28', 'Johnnie Alonso', NULL),
('42b9446a-790b-3892-2ac2-579daad24557', 'NV-47106', 'Nguyễn Kim Ngà', '2001-01-14', 0, '0396398789', '0369989699', 'Adela_Alley61@example.com', '60/15 Vạn Kiếp', '220811580951', '2018-12-28', '66 Trần Minh Quyền', 'Giám đốc', '53178', 'Sacombank', '37/05 Nguyễn Cảnh Chân', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2011-10-03 01:47:00', 'Alysa Harrell', '1980-09-04 23:01:14', 'Augustus Abreu', NULL),
('42db9027-5e76-257b-33c2-579daad24557', 'NV-05955', 'Nguyễn Thị Quế', '1972-07-15', 1, '0369877415', '0976898789', 'AbdulSoto@example.com', '11/67 Thái Thịnh', '931057953240', '2019-07-25', '36 Thạch Yên', 'Giám đốc', '82172', 'Sacombank', '2M16 -104 Nguyễn An Ninh', '469b3ece-744a-45d5-957d-e8c757976496', '1994-08-29 21:06:36', 'Camie Talbott', '1998-05-01 17:25:56', 'Albert Sutter', NULL),
('45bd4aa1-3832-3db8-d21d-086412a8ea97', 'NV-73737', 'Nguyễn Thị Quế', '1971-04-20', 2, '0369889698', '0369878969', 'Davina_Bragg91@example.com', '003 Lô B, Chung Cư Gò Dầu 2', '904703810320', '2020-09-12', '31/250 kim giang', 'Nhân viên', '17694', 'MBBank', '2/1/481 Ngọc Lâm', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2004-05-17 13:27:33', 'Trudy Ferry', '2008-05-23 06:35:22', 'Herschel Abreu', NULL),
('46325c89-599d-77ef-74f6-423b4e874d0f', 'NV-19510', 'Trần Việt Tiến', '1970-05-19', 2, '0963369896', '0369878969', 'Mckinley_Barbosa835@nowhere.com', '3c/144 quan nhân', '608336103771', '2010-01-31', 'số 3 Phùng Khoang', 'Trường phòng', '33606', 'Vietcombank', '239 Tân Thới Nhất', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2021-10-13 23:41:16', 'Judith Pinkerton', '2012-04-10 22:32:24', 'Michael Robson', NULL),
('481183cb-5a6c-795b-68f6-423b4e874d0f', 'NV-62970', 'Nguyễn Ngọc Thu', '1970-12-11', 2, '0986369879', '0369877415', 'Abney@example.com', '109 Huỳnh Thị Hai', '206369565251', '2010-05-26', '30 đường số 4', 'Giám đốc', '12641', 'VPank', '5/6A Song Hành', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2022-02-16 07:00:33', 'Toney Paradis', '1984-09-26 13:05:26', 'Mistie Musgrove', NULL),
('48147636-7e8f-6939-2580-de64d090a2c2', 'NV-86485', 'Nguyễn Việt Cương', '1960-03-01', 1, '0369878969', '0976898789', 'Tolbert@example.com', '12 Bà Lê Chân', '194476884381', '2018-06-06', '165 đường 339', 'Bảo vệ', '30069', 'ACBank', '67 ngõ 12 bồ đề long biên', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2002-11-02 17:09:50', 'Miyoko Beard', '1982-10-19 15:50:54', 'Diego Bertram', NULL),
('4852769b-3986-7c69-2077-d9ebc53aac3d', 'NV-52736', 'Trần Ánh Như', '1972-09-29', 2, '0963369896', '0396398789', 'Asher22@example.com', '128/6 Phạm Văn Hai', '461357932880', '2022-01-12', '288 Cách Mạng Tháng 8', 'Trường phòng', '17177', 'Vietcombank', '5 Quang Trung', '469b3ece-744a-45d5-957d-e8c757976496', '2001-11-27 17:04:00', 'Robbie Ali', '2022-10-24 03:55:24', 'Natasha Cuellar', NULL),
('4863fe5f-13df-4653-9041-c1ec321fe728', 'NV-08986', 'Nông Văn Đông', '1997-05-26', 1, '0396398789', '0987419510', 'AdalineZepeda@nowhere.com', '380/25 Phạm Văn Chiêu', '900295219080', '2011-05-08', '33B Phạm Ngũ Lão', 'Nhân viên', '75728', 'Vietcombank', '2/15/18 ngõ Gốc Đề', '768f8e64-7d10-20c9-967d-e8c757976496', '1977-12-07 00:04:40', 'Alecia Huskey', '2009-01-26 05:43:36', 'Kiley Wicks', NULL),
('4989ff24-23e7-7b82-b6d2-89b22d10517e', 'NV-26764', 'Đinh Kim Hương', '1999-02-27', 1, '0976898789', '0369989699', 'Bachman@example.com', '331/2 Phan Huy Ích', '143030060421', '2014-01-23', '12 phan bá vành', 'Bảo vệ', '11796', 'Vietcombank', '21 Ngũ Nhạc', '469b3ece-744a-45d5-957d-e8c757976496', '1979-10-21 15:37:26', 'Stevie Durham', '1993-01-11 10:36:59', 'Travis Abney', NULL),
('4a9854e8-12ac-72ac-2877-d9ebc53aac3d', 'NV-17834', 'Nguyễn Thị Hương', '1997-10-14', 1, '0369989699', '0369877415', 'Finn2@nowhere.com', '33B Phạm Ngũ Lão', '934004199271', '2014-01-22', '525 Nguyễn Kiệm', 'Nhân viên', '78258', 'Vietcombank', '239 Tân Thới Nhất', '768f8e64-7d10-20c9-967d-e8c757976496', '1995-05-10 17:03:07', 'Thao Zhang', '1989-05-26 03:45:32', 'Chung Read', NULL),
('4bd989e5-d74b-11ed-8de1-d8d09038d020', 'NV-99450', 'Hoàng Minh Mạnh', '2003-01-19', 2, '0963369896', '0369878969', 'Mckinley_Barbosa835@nowhere.com', '3c/144 quan nhân', '698963698789', '2010-01-31', 'số 3 Phùng Khoang', 'Trường phòng', '33606', 'Vietcombank', '239 Tân Thới Nhất', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2023-04-10 09:56:31', '', '2023-04-10 09:56:31', '', NULL),
('4bf4567b-1505-40db-dd1d-086412a8ea97', 'NV-07060', 'Nguyễn Thị Diệp', '1992-09-16', 1, '0369878963', '0963369896', 'Holloway1@example.com', '186 lê trọng tấn', '058280836260', '2010-01-11', '2/15/18 ngõ Gốc Đề', 'Bảo vệ', '84518', 'Vietcombank', '21A Lô Tư', '469b3ece-744a-45d5-957d-e8c757976496', '1979-12-29 04:31:53', 'Corey Matheson', '2014-02-15 02:33:58', 'Cheyenne Grissom', NULL),
('4bf9ecda-2d8e-1724-1d80-de64d090a2c2', 'NV-96021', 'Võ Văn Đạt', '1992-12-02', 0, '0963369896', '0396398789', 'BufordBills5@example.com', '101B A3 tập thể Nam Đồng', '802688065741', '2020-04-23', 'Ki ốt6 ct4a kđt xa la', 'Nhân viên', '82100', 'VPank', '30 đường số 4', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1988-05-26 19:26:46', 'Eloy Negron', '1998-06-30 13:44:37', 'Andria Powell', NULL),
('4c61c74b-4a9f-769e-0d35-60b3ebf808a9', 'NV-40198', 'Nguyễn Thị Liễu', '1953-01-04', 0, '0369989699', '0987419510', 'Aldo_Halcomb@example.com', '86 đường số 17', '837157993621', '2019-08-08', '574/11 Kinh Dương Vương', 'Trường phòng', '41434', 'ACBank', '58 Lâm Thị Hố', '17120d02-6ab5-3e43-18cb-66948daf6128', '1970-01-01 00:00:04', 'Floyd Bonds', '1971-01-01 00:00:04', 'Jessica Cuevas', NULL),
('4c9ebdde-5f9a-58dd-4235-0028ed526dd0', 'NV-37624', 'Trần Văn Công', '1953-01-02', 2, '0369889698', '0369878963', 'Goff@example.com', '32D1 Hoa Phượng', '295165876161', '2012-12-14', '35B đường 494', 'Giám đốc', '60554', 'MBBank', '5 Quang Trung', '17120d02-6ab5-3e43-18cb-66948daf6128', '1970-01-01 00:00:02', 'Addie Goss', '1971-01-01 00:00:02', 'Anita Cowles', NULL),
('4cc606bb-3068-7d32-3f35-0028ed526dd0', 'NV-09998', 'Nguyễn Anh Vinh', '1958-12-26', 0, '0369878963', '0369878963', 'wmunrid4218@example.com', '02- Lô F003 CC Sơn Kỳ 1', '753751577181', '2019-02-26', '02- Lô F003 CC Sơn Kỳ 1', 'Giám đốc', '62539', 'Vietcombank', '37/72 dịch vọng', '17120d02-6ab5-3e43-18cb-66948daf6128', '1981-12-27 06:34:14', 'Samual Sheffield', '1992-11-01 19:54:51', 'Kent Adame', NULL),
('4d536cce-31bf-335e-bfd2-89b22d10517e', 'NV-08636', 'Bùi Anh Phú', '1967-04-18', 2, '0987419510', '0369878969', 'Atwell@example.com', '302 Phan Văn Hớn', '996578120551', '2021-05-26', '114/14 Tô Ngọc Vân', 'Bảo vệ', '18378', 'ACBank', '574/11 Kinh Dương Vương', '768f8e64-7d10-20c9-967d-e8c757976496', '2019-10-22 12:54:05', 'Tajuana Richard', '1999-01-06 07:56:43', 'Drew Geer', NULL),
('4db9a514-6d87-2ec1-3b35-0028ed526dd0', 'NV-07076', 'Đinh Trọng Tùng', '1974-10-02', 2, '0369877415', '0369878969', 'Zenobia.Brunson@example.com', '102 lạc long quân', '710804696690', '2015-05-17', '207/21 Hồ Học Lãm', 'Giám đốc', '39782', 'Vietcombank', '38 đường số 8', '768f8e64-7d10-20c9-967d-e8c757976496', '1998-06-06 04:57:12', 'Carl Switzer', '1997-06-17 13:57:55', 'Jamie Aguiar', NULL),
('4dd0746a-6f49-64fa-1d77-d9ebc53aac3d', 'NV-27520', 'Trương Thị Bích', '1953-11-23', 2, '0369878969', '0369877415', 'Alfreda.B_Rohr@example.com', '245 Nguyễn Thị Tú', '215708671430', '2022-10-22', '104A Tân Chánh Hiệp 10', 'Trường phòng', '93310', 'MBBank', '27 đường số 10', '469b3ece-744a-45d5-957d-e8c757976496', '1970-01-01 00:05:27', 'Cole Alvarado', '1971-01-01 00:05:27', 'Anya Parnell', NULL),
('4eb131b8-234a-632f-4b35-0028ed526dd0', 'NV-66186', 'Mai Thành Công', '1953-01-27', 2, '0369878963', '0987419510', 'Cato35@example.com', 'số 3 ngách 10 ngõ 122 phố vĩnh tuy', '747022905070', '2014-07-17', '23 ngõ 26 tư đình', 'Giám đốc', '26638', 'ACBank', '483 Phạm Văn Chiêu', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1970-01-01 00:00:27', 'Birgit Christopher', '1971-01-01 00:00:27', 'Abram Penny', NULL),
('4efc95ad-2cc2-3f45-bed2-89b22d10517e', 'NV-59239', 'Hoàng Thị Hiền', '1967-11-10', 1, '0396398789', '0963369896', 'Seth_T_Acker@example.com', 'R28 Dương Thị Giang', '956564431730', '2010-03-26', '21A Lô Tư', 'Bảo vệ', '26593', 'ACBank', 'A25 Đại Từ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1978-09-28 19:39:28', 'Louie Bratcher', '2008-10-30 16:14:12', 'Ursula Manley', NULL),
('4f65f6c1-4525-16e5-4135-0028ed526dd0', 'NV-75827', 'Trịnh Ánh Nga', '1961-10-30', 2, '0369877415', '0987419510', 'Wagner@example.com', '57/63 tran quoc vượng', '424209987470', '2010-03-27', '211 Giáp Bát', 'Giám đốc', '04271', 'MBBank', '77/337 dịch vọng', '17120d02-6ab5-3e43-18cb-66948daf6128', '1977-04-02 10:34:36', 'Benedict Mcdermott', '1999-11-17 17:48:17', 'Corrie Brice', NULL),
('500b6761-1631-4f3a-c0d2-89b22d10517e', 'NV-41256', 'Trịnh Thị Chi', '1953-02-17', 0, '0369878969', '0396398789', 'Ernesto.Cody@nowhere.com', '23 ngõ 26 tư đình', '029691643090', '2010-01-07', '32D1 Hoa Phượng', 'Giám đốc', '14975', 'MBBank', '187 đường số 1', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1970-01-01 00:00:48', 'Tamera Amaya', '1971-01-01 00:00:48', 'Alecia Lemmon', NULL),
('506acf1e-5331-67a9-0d77-d9ebc53aac3d', 'NV-62848', 'Trịnh Trí Phước', '1966-01-15', 0, '0369989699', '0976898789', 'ZapataF@example.com', 'Số 19 ngõ 565 lạc long quân', '610466190390', '2011-01-05', '205 Lê Văn Chí', 'Nhân viên', '91981', 'VPank', 'số 3 Phùng Khoang', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1970-01-01 01:19:23', 'Cary Benitez', '1971-01-01 01:19:23', 'Adelaida Bergman', NULL),
('50b49b1f-3df8-4b52-db1d-086412a8ea97', 'NV-45702', 'Trần Trí Vinh', '1970-03-21', 0, '0369878969', '0369877415', 'Leslie_Grooms@nowhere.com', '9 đường số 8', '363340061540', '2016-01-04', '47 Trần Quốc Toản', 'Nhân viên', '85825', 'MBBank', '165 đường 339', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1989-02-16 12:56:43', 'Shannon Abraham', '2000-12-15 01:13:17', 'Bernardine Burleson', NULL),
('50c07587-55d5-5b36-1b77-d9ebc53aac3d', 'NV-23042', 'Trần Thị Diễm', '1982-03-17', 1, '0986369879', '0369989699', 'PhilomenaLabbe@example.com', '33 Phạm Ngũ Lão', '286792344220', '2010-01-08', '146 phố Mai Dịch', 'Bảo vệ', '73421', 'Vietcombank', '161 Thạnh Xuân 21', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1987-12-22 16:53:03', 'Archie Hooper', '2008-02-08 19:41:04', 'Emory Bishop', NULL),
('517035f8-43a9-4c59-72f6-423b4e874d0f', 'NV-45116', 'Hồ Hưng Thạch', '2001-09-23', 1, '0986369879', '0987419510', 'Grissom@example.com', '3/54A Thạnh Lộc 29', '096371961430', '2022-09-21', '3c/144 quan nhân', 'Nhân viên', '04194', 'ACBank', '17 Y Sơn 2', '17120d02-6ab5-3e43-18cb-66948daf6128', '1977-03-09 01:50:36', 'Carlie Mcduffie', '1993-04-01 17:45:02', 'Oralia Tilton', NULL),
('51b5ac10-6dea-17ad-2080-de64d090a2c2', 'NV-34964', 'Hồ Trọng Kiên', '1980-09-10', 0, '0987419510', '0396398789', 'Dollar@nowhere.com', '279 Ấp Chiến Lược', '788608640041', '2011-03-15', 'Ki ốt 4 -19t6 khu đô thị Kiến Hưng', 'Bảo vệ', '30359', 'Sacombank', '68 ngõ 254 minh khai', '469b3ece-744a-45d5-957d-e8c757976496', '2017-10-31 18:15:50', 'Herman Lindgren', '1982-01-30 21:47:44', 'Coleman Ammons', NULL),
('51c6e7d3-53bf-49ae-8a41-c1ec321fe728', 'NV-39850', 'Nguyễn Văn Long', '1985-12-22', 1, '0986369879', '0396398789', 'Shondra.Bivins9@example.com', '36 Thạch Yên', '594148244111', '2023-03-14', '860/56 Xô Viết Nghệ Tĩnh', 'Trường nhóm', '36582', 'Vietcombank', '181 Đường Số 20', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2013-09-12 14:59:07', 'Karl Bullock', '1987-02-05 14:15:59', 'Alaina Ahern', NULL),
('524751f2-1577-523d-ce1d-086412a8ea97', 'NV-50537', 'Hoàng Thị Thoa', '1985-04-16', 0, '0369877415', '0369889698', 'ShandraCarranza@nowhere.com', '207/21 Hồ Học Lãm', '047296221851', '2010-03-28', '35B đường 494', 'Trường nhóm', '49673', 'Sacombank', '83 hoa bằng', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2013-10-03 05:55:52', 'Jeffry Pease', '1996-05-04 06:57:01', 'Duncan Sisco', NULL),
('5254e49d-4368-3162-29c2-579daad24557', 'NV-93696', 'Hoàng Thị Dung', '1962-06-12', 1, '0369877415', '0987419510', 'Perkins@example.com', '35B đường 494', '339343550130', '2010-04-02', '52 đường số 17', 'Giám đốc', '65934', 'MBBank', '92/28 Vườn Lài', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2012-06-25 12:21:33', 'Cassi Atkinson', '1975-06-22 16:54:33', 'Aide Manley', NULL),
('527e293c-2185-6d0a-5580-7ed9d1ea06ea', 'NV-60083', 'Nguyễn Thị Phương', '1973-01-13', 0, '0976898789', '0963369896', 'Tomlin@nowhere.com', '52 đường số 17', '685341362780', '2013-02-03', 'số 10/79 tổ 5 yên nghĩa', 'Bảo vệ', '75687', 'ACBank', 'Số 19 ngõ 565 lạc long quân', '768f8e64-7d10-20c9-967d-e8c757976496', '2016-06-23 12:45:24', 'Iesha Jimenez', '1974-12-31 05:38:38', 'Chloe Villalobos', NULL),
('52a36f9d-42d4-6841-38c2-579daad24557', 'NV-92410', 'Bùi Đức Lĩnh', '1979-02-02', 1, '0396398789', '0369877415', 'Gough@nowhere.com', '374 Quang Trung', '416983432311', '2017-03-09', '15B/65 Lê Thánh Tôn', 'Nhân viên', '08467', 'VPank', 'Kiot 1 Chợ Yên Phúc', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2014-08-28 10:58:38', 'Esther Bennett', '1995-11-08 04:21:50', 'Catrice Hatton', NULL),
('535ddd98-1493-7909-1e80-de64d090a2c2', 'NV-07614', 'Nguyễn Ngọc Duy', '1976-09-08', 0, '0369878963', '0369989699', 'looc6@example.com', '3c/144 quan nhân', '837004645781', '2015-08-29', '47 Trần Quốc Toản', 'Trường nhóm', '48997', 'VPank', '33 Phạm Ngũ Lão', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1970-12-01 13:06:45', 'Basil Ackerman', '2005-03-05 01:22:01', 'Adan Galarza', NULL),
('53f68d51-267f-2d1e-8241-c1ec321fe728', 'NV-59230', 'Nguyễn Văn Nghĩa', '1992-12-24', 0, '0987419510', '0369877415', 'Hamblin72@nowhere.com', '574/11 Kinh Dương Vương', '836179773730', '2018-08-06', '146 Phạm Văn Chiêu', 'Trường phòng', '41832', 'Sacombank', '264/15 Thạnh Lộc 15', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1983-02-27 08:57:28', 'Denyse Ma', '1997-10-13 19:38:41', 'Isaura Hale', NULL),
('56249d42-1aee-20b3-3fc2-579daad24557', 'NV-98325', 'Nguyễn Thị Hồng', '1974-03-31', 1, '0986369879', '0396398789', 'Johnie_Gustafson8@nowhere.com', '302/78A Phan Huy Ích', '624383672030', '2020-01-10', 'số 3 ngách 10 ngõ 122 phố vĩnh tuy', 'Trường nhóm', '61341', 'Sacombank', '129 đường số 1', '768f8e64-7d10-20c9-967d-e8c757976496', '2003-01-31 20:47:28', 'Emanuel Martins', '1984-10-11 21:10:14', 'Manual Alcala', NULL),
('565c3832-2fbc-2ad0-4735-0028ed526dd0', 'NV-63378', 'Mai Trọng Triệu', '1968-01-16', 0, '0369989699', '0963369896', 'AdolfoPence@example.com', '525 Nguyễn Kiệm', '770305128291', '2016-02-17', '525 Phúc Diễn', 'Trường nhóm', '44986', 'Sacombank', '48 Thích Quảng Đức', '768f8e64-7d10-20c9-967d-e8c757976496', '1999-09-11 08:16:35', 'Ada Dailey', '1997-08-20 11:15:45', 'Roman Clinton', NULL),
('5697b103-5179-7ac3-d31d-086412a8ea97', 'NV-63655', 'Hồ Vân Phượng', '1986-08-23', 2, '0963369896', '0396398789', 'Peek@example.com', '567/66 Lê Văn Khương', '186777168400', '2023-02-10', '69/57 Nguyễn Gia Trí', 'Giám đốc', '18295', 'ACBank', '84 Nguyễn Minh Hoàng', '469b3ece-744a-45d5-957d-e8c757976496', '2002-11-29 14:29:03', 'Gerry Hutchens', '2009-02-25 00:26:57', 'Vincenzo Homan', NULL),
('56aaf263-3355-23ea-b8d2-89b22d10517e', 'NV-51563', 'Vũ Văn Dương', '1985-03-26', 2, '0963369896', '0369878963', 'Arthur@example.com', '33B Phạm Ngũ Lão', '782421241461', '2016-08-12', '11/67 Thái Thịnh', 'Trường phòng', '37873', 'Vietcombank', '128/6 Phạm Văn Hai', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2010-04-21 10:33:03', 'Rodger Crawford', '1988-09-20 15:48:03', 'Adaline Shah', NULL),
('56dce332-76f0-6b9b-5080-7ed9d1ea06ea', 'NV-91335', 'Đinh Văn Vinh', '1964-05-26', 0, '0369889698', '0369878969', 'Brinkman28@example.com', 'số 10/79 tổ 5 yên nghĩa', '777038713981', '2014-03-20', '118 Đông Hưng Thuận 06', 'Nhân viên', '51365', 'MBBank', '33 Phạm Ngũ Lão', '469b3ece-744a-45d5-957d-e8c757976496', '1970-08-18 19:20:38', 'Amiee Pond', '2012-09-12 19:42:19', 'Lester Cohn', NULL),
('57cdf8c4-47e3-5560-7e41-c1ec321fe728', 'NV-24852', 'Hồ Thị Diễm', '1975-07-02', 1, '0369889698', '0369889698', 'Schuler@example.com', '39/65 mai dịch', '114218608511', '2010-03-29', '783/1 Hà Huy Giáp', 'Trường phòng', '12831', 'ACBank', '5 Quang Trung', '768f8e64-7d10-20c9-967d-e8c757976496', '1997-09-22 06:34:04', 'Kennith Carswell', '2000-07-24 14:20:22', 'Albert Mclean', NULL),
('57dc4273-5c51-4aea-4d35-0028ed526dd0', 'NV-00725', 'Nguyễn Thị Tuyết', '1991-10-20', 2, '0369877415', '0369877415', 'LucianaKeaton@example.com', '48/299 Hoàng Mai', '330895570351', '2010-06-06', '129 đường số 1', 'Trường phòng', '40750', 'Sacombank', '102/14 Lê Văn Thọ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1970-01-28 18:08:36', 'Jamie Sloan', '2010-09-08 14:43:22', 'Cesar Singletary', NULL),
('57e65423-37f0-74b0-71f6-423b4e874d0f', 'NV-32311', 'Nguyễn Thị Nhài', '1971-05-13', 1, '0396398789', '0963369896', 'Nathaniel.Hannon@example.com', '109 Huỳnh Thị Hai', '651988684751', '2016-10-01', '11/15 Lương Định Của', 'Giám đốc', '55189', 'ACBank', '12 Bà Lê Chân', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1996-07-09 03:23:11', 'Ike Hernandez', '2010-01-16 17:41:52', 'Rosina Adair', NULL),
('58e49fff-2a42-4ce7-1c77-d9ebc53aac3d', 'NV-01631', 'Hồ Linh Hồng', '1968-01-24', 0, '0976898789', '0369878969', 'Cowley951@example.com', 'A25 Đại Từ', '170720826820', '2011-11-04', '248/16 Nguyễn Thái Bình', 'Trường phòng', '77270', 'VPank', '33B Phạm Ngũ Lão', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1975-10-25 13:28:14', 'Paris Lemieux', '2010-09-21 01:33:27', 'Alan Sargent', NULL),
('592aba45-4643-52ff-c1d2-89b22d10517e', 'NV-17544', 'Nguyễn Tiến Thông', '1975-11-26', 0, '0986369879', '0987419510', 'jrhjvj2@nowhere.com', '25 đường số 9', '454717074390', '2022-10-18', '73 Kim Hoa', 'Giám đốc', '95341', 'Sacombank', 'A25 Đại Từ', '768f8e64-7d10-20c9-967d-e8c757976496', '1972-05-13 17:02:24', 'Hugh Angulo', '2015-10-08 08:16:48', 'Daria Dougherty', NULL),
('595e7d51-318c-39e8-1377-d9ebc53aac3d', 'NV-88652', 'Trần Thị Diễm', '1961-02-03', 0, '0369889698', '0976898789', 'jfhbwpxk.jxmonkyjvl@example.com', 'R28 Dương Thị Giang', '748611947740', '2021-02-27', '860/56 Xô Viết Nghệ Tĩnh', 'Trường phòng', '19450', 'Vietcombank', '331/2 Phan Huy Ích', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1982-03-02 08:47:33', 'Eldridge Cornett', '1979-10-27 04:18:16', 'Fermina Fields', NULL),
('5a841b92-791c-78df-5180-7ed9d1ea06ea', 'NV-99448', 'Nông Thị Liễu', '1995-06-18', 2, '0369989699', '0369877415', 'Suggs@example.com', '33B Phạm Ngũ Lão', '173331039910', '2015-08-23', '227 Đường Số 1', 'Giám đốc', '18486', 'ACBank', '07 Hoàng Hữu Nam', '469b3ece-744a-45d5-957d-e8c757976496', '1988-07-15 09:14:42', 'Dia Casteel', '1979-03-15 08:51:42', 'Abdul Rainey', NULL),
('5c7f0ec4-77f2-3794-cf1d-086412a8ea97', 'NV-34078', 'Nguyễn Thanh Mỹ', '1955-05-18', 1, '0987419510', '0369877415', 'FriedaAbreu99@example.com', '77/337 dịch vọng', '103020458551', '2011-06-26', '783/1 Hà Huy Giáp', 'Trường nhóm', '49252', 'Sacombank', '165 đường 339', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1970-01-01 00:14:28', 'Joshua Villasenor', '1971-01-01 00:14:28', 'Judson Oh', NULL),
('5c85f9f2-1de1-4f0a-3e35-0028ed526dd0', 'NV-05813', 'Đinh Tú Hương', '1995-08-01', 0, '0369989699', '0963369896', 'Jeffery_Nieves@example.com', '33B Phạm Ngũ Lão', '397022719631', '2017-11-13', '213 Trần Cung', 'Trường phòng', '45905', 'MBBank', '94 việt hưng', '469b3ece-744a-45d5-957d-e8c757976496', '2022-08-13 03:41:09', 'Julio Gillis', '2023-04-10 10:04:01', 'Admin', NULL),
('5d1472a0-d74b-11ed-8de1-d8d09038d020', 'NV-99451', 'Hoàng Minh Hạnh', '1965-10-07', 0, '0987419510', '0369878963', 'Abel@nowhere.com', '33B Phạm Ngũ Lão', '972979670451', '2017-11-10', '25 Ngõ 2 Đại Từ', 'Trường nhóm', '50026', 'MBBank', '49 Nguyễn Trung Ngạn', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2023-04-10 09:57:00', '', '2023-04-10 09:57:00', '', NULL),
('5dc832b0-169a-1395-37c2-579daad24557', 'NV-97554', 'Nguyễn Thị Châu', '1953-01-22', 1, '0963369896', '0963369896', 'StaciaMcneal@example.com', '21 Ngũ Nhạc', '890716664290', '2016-06-11', '106 Nguyễn Thị Sáu', 'Bảo vệ', '98036', 'Sacombank', '638 Tỉnh Lộ 10', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1970-01-01 00:00:22', 'Basil Mahon', '1971-01-01 00:00:22', 'Randell Conaway', NULL),
('5de704c2-573f-1a71-1a80-de64d090a2c2', 'NV-95834', 'Nguyễn Kim Chi', '1953-01-07', 1, '0976898789', '0369889698', 'Barrett_Mcgowan@example.com', '220 Trần Thị Cờ', '893749806491', '2010-11-13', 'Số 19 ngõ 565 lạc long quân', 'Nhân viên', '74078', 'MBBank', '102/14 Lê Văn Thọ', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1970-01-01 00:00:07', 'Federico Lujan', '1971-01-01 00:00:07', 'Abe Tibbs', NULL),
('5eaa6527-768d-3ae7-1977-d9ebc53aac3d', 'NV-73385', 'Trần Thành Định', '1956-09-21', 2, '0369889698', '0369878969', 'awpq00@example.com', '37/05 Nguyễn Cảnh Chân', '082816595081', '2016-01-03', 'B240 ĐHT 11', 'Giám đốc', '89689', 'Vietcombank', '240E Tô Ngọc Vân', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1978-01-10 02:08:06', 'Norine Mackey', '2001-07-08 07:09:41', 'Mike Burgos', NULL),
('5edb2be2-7849-4909-c2d2-89b22d10517e', 'NV-90001', 'Nguyễn Việt Nhanh', '1953-01-05', 0, '0369889698', '0369878969', 'Buck@nowhere.com', 'Kiot 22 – HH03D, khu đô thị Thanh Hà', '924098038430', '2017-03-16', '12 Bà Lê Chân', 'Nhân viên', '08861', 'Vietcombank', '104 nhà K, ngõ 72 Lĩnh Nam', '17120d02-6ab5-3e43-18cb-66948daf6128', '1970-01-01 00:00:05', 'Abe Phan', '1971-01-01 00:00:05', 'Apryl Archibald', NULL),
('5f03d745-7702-1c85-2bc2-579daad24557', 'NV-23066', 'Đinh Thị Phượng', '1973-06-16', 0, '0976898789', '0369878963', 'Calkins615@example.com', '239 Tân Thới Nhất', '020547979220', '2015-09-19', '36 Thạch Yên', 'Giám đốc', '12554', 'Sacombank', '185 phố nam dư', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1987-12-04 20:57:28', 'Sanford Abbott', '1980-10-10 11:40:33', 'Alexis Goulet', NULL),
('5f4b1d0a-247b-7049-4435-0028ed526dd0', 'NV-59011', 'Đinh Thị Hà', '1953-01-07', 0, '0369989699', '0986369879', 'Pressley@example.com', '302/78A Phan Huy Ích', '878142186121', '2011-10-30', '102/14 Lê Văn Thọ', 'Bảo vệ', '75349', 'ACBank', '223 Thanh Nhàn', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1970-01-01 00:00:07', 'Francisco Polanco', '1971-01-01 00:00:07', 'Darryl Julian', NULL),
('5fab4ff7-1b8e-64d0-1880-de64d090a2c2', 'NV-87488', 'Nguyễn Thị Hương', '1970-09-13', 1, '0369878969', '0369878969', 'ktercnnp_okcisx@example.com', '69/57 Nguyễn Gia Trí', '068234919371', '2020-11-19', '220 Trần Thị Cờ', 'Giám đốc', '98918', 'VPank', 'số 2 Nguyễn Hiền', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2011-11-09 23:02:59', 'Tanner Butler', '2017-11-05 21:48:43', 'Gregg Fulmer', NULL),
('5fb9392a-4ad5-1fe7-76f6-423b4e874d0f', 'NV-41156', 'Nguyễn Quốc Lương', '2002-07-18', 1, '0963369896', '0369989699', 'Durr@example.com', '15/7 Huỳnh Thị Hai', '553073579931', '2017-11-24', '15/15A25', 'Trường nhóm', '94267', 'Vietcombank', '239 Tân Thới Nhất', '768f8e64-7d10-20c9-967d-e8c757976496', '2009-01-13 17:27:05', 'Anita Somers', '2002-05-25 01:32:15', 'Emerson Carmichael', NULL),
('5fd0a411-5945-70f7-4a35-0028ed526dd0', 'NV-31368', 'Hồ Quang Tuyền', '1970-02-20', 1, '0369989699', '0963369896', 'JaunitaSouthard@example.com', 'số 3 Phùng Khoang', '706164010031', '2010-02-28', '2M16 -104 Nguyễn An Ninh', 'Bảo vệ', '84139', 'Sacombank', '33 Phạm Ngũ Lão', '17120d02-6ab5-3e43-18cb-66948daf6128', '2016-09-12 09:25:32', 'Adolfo Bolduc', '2022-02-27 19:18:03', 'Tamera Lemieux', NULL),
('60fa924e-77de-55f3-2377-d9ebc53aac3d', 'NV-29975', 'Hồ Khánh Huyền', '1957-12-29', 1, '0369878969', '0369877415', 'Meyer@example.com', '165 đường 339', '495273827371', '2017-11-28', '207/51 Hồ Học Lãm', 'Giám đốc', '16726', 'ACBank', '17 Y Sơn 2', '469b3ece-744a-45d5-957d-e8c757976496', '1979-03-08 13:24:22', 'Rufina Ali', '2005-02-21 09:56:11', 'Danny Baum', NULL),
('611bb57c-5f6c-434c-c5d2-89b22d10517e', 'NV-65540', 'Nguyễn Trí Quốc', '1960-06-25', 2, '0963369896', '0976898789', 'AndreasPatel65@example.com', '264/15 Thạnh Lộc 15', '564370315711', '2013-01-07', '205 Lê Văn Chí', 'Bảo vệ', '43134', 'Sacombank', 'P57 A4 ngõ 120 Hoàng Quốc Việt', '768f8e64-7d10-20c9-967d-e8c757976496', '1970-01-01 00:45:33', 'Darron Camp', '1971-01-01 00:45:33', 'Israel Abernathy', NULL),
('613afd47-2fc1-15ed-0735-60b3ebf808a9', 'NV-81804', 'Nguyễn Việt Thành', '1953-01-06', 2, '0369878969', '0369878963', 'Bolen@nowhere.com', '187 đường số 1', '234808233681', '2014-10-08', '2/15/18 ngõ Gốc Đề', 'Bảo vệ', '13897', 'VPank', '60 Thạnh Lộc 31', '17120d02-6ab5-3e43-18cb-66948daf6128', '1970-01-01 00:00:06', 'Ambrose Crowley', '1971-01-01 00:00:06', 'Kirk Ernst', NULL),
('619ecbc4-37bc-19ea-6ff6-423b4e874d0f', 'NV-15405', 'Vũ Thị Bích', '1953-04-01', 2, '0987419510', '0369989699', 'Engel718@nowhere.com', '279 Ấp Chiến Lược', '377421941860', '2018-04-30', '149 ngõ 670 nguyễn khoái', 'Trường phòng', '33580', 'Sacombank', '71 Thạnh Lộc 16', '768f8e64-7d10-20c9-967d-e8c757976496', '1970-01-01 00:01:31', 'Ryan Mcclendon', '1971-01-01 00:01:31', 'Carlyn Abel', NULL),
('623727c0-4fb7-573d-c3d2-89b22d10517e', 'NV-17327', 'Hồ Tiến Thịnh', '1962-11-04', 0, '0369878969', '0369878963', 'Celina.Halcomb@example.com', '33 Phạm Ngũ Lão', '323457937330', '2016-06-20', '15B/65 Lê Thánh Tôn', 'Trường nhóm', '76306', 'Vietcombank', '33 Phạm Ngũ Lão', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2007-01-08 08:47:21', 'Caryn Abreu', '1999-10-25 19:18:08', 'Murray Lombardo', NULL),
('62563348-7bd5-6519-3c35-0028ed526dd0', 'NV-81826', 'Nguyễn Văn Công', '1954-09-22', 0, '0396398789', '0369878963', 'aweyzjpd3111@example.com', '9 đường số 8', '741635714230', '2013-02-18', '567/66 Lê Văn Khương', 'Trường phòng', '61469', 'MBBank', '18/33 Văn Chương 2', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1989-01-21 00:42:46', 'Bridgette Conley', '1971-09-07 21:44:38', 'Rory Burchfield', NULL),
('62af2231-78a7-7caa-cd1d-086412a8ea97', 'NV-02367', 'Nông Văn Phúc', '1981-08-11', 2, '0369878969', '0369878969', 'Kiefer@nowhere.com', '25 Ngõ 2 Đại Từ', '806406329231', '2012-04-29', '223 Thanh Nhàn', 'Giám đốc', '78096', 'VPank', '68 ngõ 254 minh khai', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1972-10-24 06:06:12', 'Christian Abernathy', '2019-05-13 12:39:34', 'Vance Blaine', NULL),
('6399a2a5-2afd-3384-da1d-086412a8ea97', 'NV-71380', 'Trần Thị Trà', '1979-09-27', 2, '0369878963', '0369877415', 'Crabtree@example.com', '36 Thạch Yên', '056592945330', '2011-03-26', '11/15 Lương Định Của', 'Trường phòng', '78955', 'ACBank', '35B đường 494', '469b3ece-744a-45d5-957d-e8c757976496', '2017-01-28 22:20:07', 'Lexie Holman', '2005-09-11 22:09:07', 'Camilla Henke', NULL),
('63efa6f8-d74b-11ed-8de1-d8d09038d020', 'NV-99452', 'Trần Trí Anh', '1956-03-12', 0, '0369989699', '0396398789', 'xtjlpw4@example.com', '369 Bà Hạt', '282848716260', '2015-01-15', '86 đường số 17', 'Trường phòng', '16483', 'Vietcombank', '165 đường 339', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2023-04-10 09:57:11', '', '2023-04-10 09:57:11', '', NULL),
('6485b64f-7835-65a4-8041-c1ec321fe728', 'NV-75692', 'Trần Quang Bằng', '1953-03-03', 1, '0963369896', '0369889698', 'Tackett@example.com', '149 ngõ 670 nguyễn khoái', '736058651871', '2013-08-04', '102 lạc long quân', 'Bảo vệ', '99830', 'Vietcombank', '17 Y Sơn 2', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1970-01-01 00:01:02', 'Abby Marcum', '1971-01-01 00:01:02', 'Melvin Sommers', NULL),
('65ecf5c2-5298-156e-d51d-086412a8ea97', 'NV-60381', 'Nguyễn Văn Linh', '1953-01-10', 2, '0986369879', '0369989699', 'Mindy.Albrecht@nowhere.com', '697 Vũ Tông Phan', '109528414611', '2013-04-22', '223 Thanh Nhàn', 'Trường phòng', '51693', 'Vietcombank', 'Số 60 ngõ 107 Lĩnh Nam', '469b3ece-744a-45d5-957d-e8c757976496', '1970-01-01 00:00:10', 'Bula Andrews', '1971-01-01 00:00:10', 'Tamiko Lance', NULL),
('66ef0b11-1892-1443-1877-d9ebc53aac3d', 'NV-48812', 'Trương Thị Thu', '1965-02-07', 0, '0369889698', '0369878969', 'RobertoFinney@example.com', '165 hoàng hoa thám', '478945693331', '2014-07-13', '95 Tân Lập 1', 'Trường nhóm', '14305', 'Vietcombank', '25 Ngõ 2 Đại Từ', '469b3ece-744a-45d5-957d-e8c757976496', '1980-06-21 07:36:30', 'Lara Moran', '2015-01-17 02:01:14', 'Jutta Wiseman', NULL),
('677132b4-2a33-68d1-26c2-579daad24557', 'NV-29604', 'Trần Ánh Liễu', '1969-11-08', 0, '0369989699', '0369889698', 'Barr@nowhere.com', 'Số 3 ngõ 13 Lĩnh Nam', '273278293581', '2013-03-10', '36 Thạch Yên', 'Giám đốc', '15938', 'VPank', '3c/144 quan nhân', '17120d02-6ab5-3e43-18cb-66948daf6128', '2017-12-08 14:47:42', 'Erasmo Joe', '2023-01-26 18:49:19', 'Edgar Adler', NULL),
('67e3818b-56b7-4eb0-5c80-7ed9d1ea06ea', 'NV-17455', 'Hồ Việt Quân', '1953-02-10', 0, '0369878969', '0963369896', 'qmkigm6667@nowhere.com', '18/33 Văn Chương 2', '616318218640', '2015-06-28', 'số 3 Phùng Khoang', 'Bảo vệ', '25891', 'Vietcombank', '94 việt hưng', '142cb08f-7c31-21fa-8e90-67245e8b283e', '1970-01-01 00:00:41', 'Bernie Neil', '1971-01-01 00:00:41', 'Mauro Booker', NULL),
('692647c6-d74b-11ed-8de1-d8d09038d020', 'NV-99453', 'Hồ Trọng Kiên', '1980-09-10', 0, '0987419510', '0396398789', 'Dollar@nowhere.com', '279 Ấp Chiến Lược', '788608640041', '2011-03-15', 'Ki ốt 4 -19t6 khu đô thị Kiến Hưng', 'Bảo vệ', '30359', 'Sacombank', '68 ngõ 254 minh khai', '469b3ece-744a-45d5-957d-e8c757976496', '2023-04-10 09:57:20', '', '2023-04-10 09:57:20', '', NULL),
('6a50ecc3-384e-2a54-2177-d9ebc53aac3d', 'NV-10028', 'Nông Thị Dương', '1993-12-25', 1, '0369878963', '0369877415', 'ShelbyBoisvert7@example.com', '36 Thạch Yên', '082262292240', '2011-09-19', '95 Tân Thới Nhất 05', 'Trường nhóm', '40470', 'MBBank', '07 Hoàng Hữu Nam', '768f8e64-7d10-20c9-967d-e8c757976496', '2003-05-06 14:10:58', 'Sheena Ambrose', '1988-02-27 17:09:54', 'Lucie Whaley', NULL),
('6a763a51-4322-5c5a-b5d2-89b22d10517e', 'NV-65554', 'Nguyễn Văn Thắng', '1956-11-08', 2, '0369878963', '0987419510', 'LambF@nowhere.com', '52 đường số 17', '536058144721', '2011-09-15', '36 Thạch Yên', 'Trường nhóm', '73979', 'Vietcombank', 'R28 Dương Thị Giang', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1986-03-11 06:15:48', 'Joeann Garcia', '2004-03-17 04:36:12', 'Percy Valdes', NULL),
('6b12b154-39d3-1a5b-2280-de64d090a2c2', 'NV-00792', 'Nguyễn Khánh Điệp', '1971-08-10', 2, '0987419510', '0963369896', 'RoscoeAbrams53@example.com', '186 lê trọng tấn', '817321263321', '2013-12-04', '157B Đường TX 21', 'Trường phòng', '96972', 'Vietcombank', '211 Giáp Bát', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2018-10-21 09:48:30', 'Arnetta Abernathy', '1982-07-22 20:21:07', 'Dion Lundy', NULL),
('6b550b8f-7ff9-51bc-0f77-d9ebc53aac3d', 'NV-15692', 'Bùi Thị Lan', '1982-05-09', 2, '0369878969', '0369878963', 'EdmundBenitez631@example.com', '15/15A25', '599492536101', '2022-11-12', '47 Trần Quốc Toản', 'Trường nhóm', '48685', 'MBBank', '87/117/6 Nguyễn Sỹ Sách', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1996-06-21 20:02:26', 'Alfonzo Bohn', '2007-10-02 17:20:20', 'Leonora Houser', NULL),
('6b6ba1f9-d74b-11ed-8de1-d8d09038d020', 'NV-99454', 'Trần Thị Phượng', '1986-12-21', 0, '0369889698', '0963369896', 'DenverSewell899@example.com', '128/6 Phạm Văn Hai', '946536047170', '2022-08-20', '187 đường số 1', 'Trường nhóm', '90562', 'ACBank', '328 Lê Văn Việt', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2023-04-10 09:57:24', '', '2023-04-10 09:59:11', 'Admin', NULL),
('6b76d607-7d60-38a2-5680-7ed9d1ea06ea', 'NV-46329', 'Trần Văn Tiến', '1956-10-12', 1, '0396398789', '0976898789', 'CharlesGrimm@example.com', '83 hoa bằng', '192369041620', '2021-07-05', '52 đường số 17', 'Trường phòng', '57906', 'Sacombank', '18c Trần Thái Tông', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1971-11-29 10:09:56', 'Johnson Adair', '2019-08-29 10:56:42', 'Austin Keaton', NULL),
('6bb2a723-7c18-1df2-0b35-60b3ebf808a9', 'NV-41065', 'Nguyễn Thị Chi', '1982-05-17', 2, '0396398789', '0986369879', 'Abraham@example.com', '84 Nguyễn Minh Hoàng', '012195702240', '2011-12-25', '177 ngõ 467 lĩnh nam', 'Bảo vệ', '82569', 'MBBank', '77/337 dịch vọng', '768f8e64-7d10-20c9-967d-e8c757976496', '1974-10-21 04:09:59', 'Everett Mccullough', '1998-02-16 18:48:26', 'Abby Kohler', NULL),
('6c5b9fe7-14c9-3bb5-b4d2-89b22d10517e', 'NV-97950', 'Nguyễn Thị Đan', '1953-09-08', 2, '0396398789', '0369989699', 'Salley69@nowhere.com', '118 Đông Hưng Thuận 06', '145321970800', '2010-01-05', '27A Miếu Gò Xoài', 'Bảo vệ', '48708', 'VPank', '84A Tôn Thất Hiệp', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '2006-12-05 23:00:17', 'Addie Tyner', '2010-11-24 10:52:16', 'Dudley Rowan', NULL),
('6c80a684-1cb5-41af-ff34-60b3ebf808a9', 'NV-26972', 'Mai Văn Nhanh', '1980-11-22', 0, '0987419510', '0976898789', 'Sanford549@nowhere.com', '234/28 Phạm Văn Hân', '956525825240', '2016-12-10', '57/63 tran quoc vượng', 'Giám đốc', '27381', 'VPank', '52 Võ Thị Thừa', '17120d02-6ab5-3e43-18cb-66948daf6128', '2020-10-14 20:22:53', 'Kathyrn Beatty', '1996-04-26 17:58:23', 'Abram Patten', NULL),
('6d489b13-7396-7986-1577-d9ebc53aac3d', 'NV-92040', 'Trần Trí Khánh', '1968-11-10', 2, '0369878963', '0963369896', 'MayeAbrams@example.com', '33 Phạm Ngũ Lão', '603397870270', '2015-11-02', '33 Phạm Ngũ Lão', 'Giám đốc', '14396', 'Sacombank', '6D6 khu giãn dân yên phúc', '17120d02-6ab5-3e43-18cb-66948daf6128', '1976-08-08 12:26:10', 'Carmine Newell', '2021-11-24 14:17:13', 'Arnold Abrams', NULL),
('6d7def1b-4b7e-52aa-8f41-c1ec321fe728', 'NV-30877', 'Nông Linh Chi', '1994-09-22', 1, '0369878963', '0396398789', 'Manuel@nowhere.com', '48 Thích Quảng Đức', '551879566910', '2010-02-08', '104 nhà K, ngõ 72 Lĩnh Nam', 'Bảo vệ', '44965', 'ACBank', '413/22 Lê Văn Sỹ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2008-08-23 14:50:20', 'Hugh Willson', '2010-03-21 06:00:40', 'Lorita Adams', NULL),
('6dcdb6b6-273a-6aaa-8541-c1ec321fe728', 'NV-17246', 'Trần Thị Thư', '1955-05-11', 1, '0396398789', '0987419510', 'Staley@nowhere.com', 'Ki ốt6 ct4a kđt xa la', '233488215281', '2018-01-26', '3c/144 quan nhân', 'Nhân viên', '44796', 'Vietcombank', '205 Lê Văn Chí', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1990-08-19 01:29:24', 'Irwin Archibald', '1986-05-04 09:08:59', 'Reta Wilbanks', NULL),
('6e3f7a8c-2f78-16a9-36c2-579daad24557', 'NV-83245', 'Nông Văn Thăng', '2002-10-27', 0, '0369878963', '0369989699', 'tsbgmdqr.tuqw@nowhere.com', '638/74A HL80B', '546594828781', '2016-11-30', '413/22 Lê Văn Sỹ', 'Trường phòng', '31333', 'Sacombank', '312 Phạm Văn Bạch', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1999-05-26 06:35:01', 'Deena Carrier', '1994-12-06 00:16:25', 'Joannie Stubbs', NULL),
('6f1014db-2ff0-613b-bdd2-89b22d10517e', 'NV-75921', 'Hoàng Ánh Bình', '1957-07-10', 0, '0987419510', '0963369896', 'Keith51@nowhere.com', '16/49 Trần Cung', '681746229310', '2013-07-21', '12 Bà Lê Chân', 'Trường phòng', '79380', 'Sacombank', '18c Trần Thái Tông', '469b3ece-744a-45d5-957d-e8c757976496', '1970-01-01 00:27:32', 'Ambrose Nieto', '1971-01-01 00:27:32', 'Abigail Barney', NULL),
('6f51ea57-13b2-139f-1177-d9ebc53aac3d', 'NV-89828', 'Trần Thị Nguyệt', '1988-07-30', 0, '0976898789', '0369877415', 'Duval@example.com', '72 ngõ 49 thúy lĩnh', '275389459111', '2012-04-09', 'Kiot 22 – HH03D, khu đô thị Thanh Hà', 'Trường phòng', '49031', 'MBBank', '101B A3 tập thể Nam Đồng', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1995-09-08 08:55:12', 'Tess Townsend', '1992-12-28 06:59:38', 'Agueda Camp', NULL),
('707e1336-6584-55de-8341-c1ec321fe728', 'NV-83415', 'Nguyễn Thành Phương', '1953-03-30', 1, '0369878963', '0369889698', 'Hooks24@example.com', '33B Phạm Ngũ Lão', '856142849811', '2010-02-05', '326 Nguyễn Trãi', 'Trường nhóm', '19671', 'Vietcombank', '160 Thạnh Lộc 16', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1970-01-01 00:01:29', 'Marni Woodson', '1971-01-01 00:01:29', 'Bryon Vigil', NULL),
('70aead00-2db5-77f7-2277-d9ebc53aac3d', 'NV-67462', 'Nguyễn Thị Trâm', '1981-08-06', 2, '0369878969', '0369989699', 'AnnamarieKeen26@nowhere.com', '37/05 Nguyễn Cảnh Chân', '815590905920', '2016-07-06', 'Số 37 DV2 khu đô thị văn phú', 'Nhân viên', '30534', 'ACBank', '49 Nguyễn Trung Ngạn', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1983-07-13 15:44:44', 'Alba Spooner', '2011-05-16 01:04:58', 'Crysta Leyva', NULL),
('721b7460-7378-2203-0435-60b3ebf808a9', 'NV-24539', 'Trần Kim Hồng', '1999-05-29', 1, '0369989699', '0369878963', 'Cash@example.com', '161 Thạnh Xuân 21', '069941717390', '2011-03-08', '52 Võ Thị Thừa', 'Trường nhóm', '32387', 'Sacombank', '248/16 Nguyễn Thái Bình', '469b3ece-744a-45d5-957d-e8c757976496', '1980-09-30 06:52:52', 'Jeanette Friedman', '1982-05-02 11:58:23', 'Bernardo Adams', NULL),
('73dc79e1-1ccb-35a6-0235-60b3ebf808a9', 'NV-66109', 'Hồ Trọng Linh', '1971-01-22', 1, '0369889698', '0369889698', 'rvxkhcgk5666@example.com', '11/67 Thái Thịnh', '493245306380', '2021-09-22', '95/33 Lê Tấn Bê', 'Bảo vệ', '91853', 'ACBank', '2M16 -104 Nguyễn An Ninh', '768f8e64-7d10-20c9-967d-e8c757976496', '1974-08-25 19:01:17', 'Emmett Musgrove', '2019-02-16 11:40:37', 'Allan Canales', NULL),
('75ec2fe2-5965-48e6-9141-c1ec321fe728', 'NV-58058', 'Nguyễn Ánh Tuệ', '2002-12-07', 2, '0976898789', '0976898789', 'EulahTenney362@example.com', '110 Nguyễn Đình Chiểu', '278704996541', '2019-08-13', 'Số 4 ngõ 278 Thái Hà', 'Nhân viên', '46137', 'Sacombank', '32D1 Hoa Phượng', '768f8e64-7d10-20c9-967d-e8c757976496', '2003-01-21 08:25:57', 'Mckenzie Hailey', '1977-02-06 09:48:20', 'Babara Chin', NULL),
('762cf9e5-356b-56d7-5f80-7ed9d1ea06ea', 'NV-40191', 'Nguyễn Văn Cường', '1969-11-02', 0, '0396398789', '0369989699', 'Adina.Andres95@example.com', '149b/e Tô Ngọc Vân', '263610334580', '2014-09-10', '33 Phạm Ngũ Lão', 'Bảo vệ', '06790', 'Sacombank', '77/337 dịch vọng', '768f8e64-7d10-20c9-967d-e8c757976496', '1970-01-01 01:42:30', 'Adriene Carnahan', '1971-01-01 01:42:30', 'Vinnie Ryan', NULL),
('76b3b772-27f3-37bf-75f6-423b4e874d0f', 'NV-58360', 'Nguyễn Hưng Trọng', '1972-06-20', 0, '0963369896', '0369889698', 'LaritaBoss345@nowhere.com', '181 Đường Số 20', '615430369510', '2011-11-08', '149 ngõ 670 nguyễn khoái', 'Giám đốc', '71766', 'MBBank', '600 Nguyễn Kiệm', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '1998-09-23 23:58:53', 'Issac Brent', '1982-01-04 15:37:04', 'Abel Dowd', NULL),
('76cc3313-3932-7e97-4635-0028ed526dd0', 'NV-10674', 'Nông Việt Bằng', '1973-10-30', 0, '0369877415', '0963369896', 'TraceyBorders4@nowhere.com', 'Ki ốt6 ct4a kđt xa la', '631958565150', '2022-09-30', '77/337 dịch vọng', 'Trường nhóm', '60656', 'ACBank', '248/16 Nguyễn Thái Bình', '17120d02-6ab5-3e43-18cb-66948daf6128', '1987-05-25 01:16:59', 'Despina Aldridge', '1984-06-27 21:44:53', 'Agatha Alonso', NULL),
('77d03350-6ba4-226c-77f6-423b4e874d0f', 'NV-13351', 'Vũ Việt Danh', '1955-05-10', 0, '0369877415', '0369989699', 'Edwardo.HAbel@example.com', '783/1 Hà Huy Giáp', '813808737120', '2020-02-21', '525/1/2 Quang Trung', 'Bảo vệ', '16403', 'MBBank', '36 Phan Đình Giót', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1970-01-01 00:14:20', 'Alix Wolfe', '1971-01-01 00:14:20', 'Mitzie Abreu', NULL),
('78b1d514-338c-3cdc-8641-c1ec321fe728', 'NV-10623', 'Trịnh Thị Băng', '1953-01-08', 2, '0976898789', '0986369879', 'Winkler51@nowhere.com', '38 Đường Tân Thới Hiệp 21', '871852378170', '2020-12-10', '36 Thạch Yên', 'Trường phòng', '89158', 'VPank', '33B Phạm Ngũ Lão', '17120d02-6ab5-3e43-18cb-66948daf6128', '1970-01-01 00:00:08', 'Michel Rose', '1971-01-01 00:00:08', 'Dewey Morrell', NULL),
('7976650d-4e86-2615-8c41-c1ec321fe728', 'NV-85653', 'Nguyễn Thị Lan', '1961-04-19', 2, '0963369896', '0986369879', 'Barnett@example.com', '2/1/481 Ngọc Lâm', '739763516331', '2012-01-10', '37/72 dịch vọng', 'Bảo vệ', '71337', 'MBBank', '07 Hoàng Hữu Nam', '469b3ece-744a-45d5-957d-e8c757976496', '1971-11-28 22:46:05', 'Addie August', '1990-06-19 07:25:08', 'Mitchell Buckley', NULL),
('79806d6f-4830-6311-2577-d9ebc53aac3d', 'NV-05852', 'Nguyễn Thị Điệp', '1955-05-04', 0, '0976898789', '0369889698', 'HopperN@nowhere.com', '49 Nguyễn Trung Ngạn', '604201029941', '2021-03-12', 'Kiot 22 – HH03D, khu đô thị Thanh Hà', 'Giám đốc', '43746', 'VPank', 'Số 4 ngõ 278 Thái Hà', '17120d02-6ab5-3e43-18cb-66948daf6128', '1970-01-01 00:14:14', 'Blake Yoder', '1971-01-01 00:14:14', 'Stan Lanier', NULL),
('79dadd0d-69fa-5e30-35c2-579daad24557', 'NV-71902', 'Mai Vân Phương', '1973-11-09', 2, '0976898789', '0986369879', 'ourbk6238@nowhere.com', '525 Phúc Diễn', '165562996940', '2020-12-24', '525 Phúc Diễn', 'Giám đốc', '26203', 'Sacombank', '240E Tô Ngọc Vân', '17120d02-6ab5-3e43-18cb-66948daf6128', '1986-11-25 08:48:07', 'Craig Moulton', '2004-11-29 16:19:43', 'Carissa Becerra', NULL),
('7a1114ad-76c4-3734-1f77-d9ebc53aac3d', 'NV-73553', 'Nguyễn Kim Diệp', '1960-09-09', 2, '0369989699', '0369878963', 'Dedra.Laws888@nowhere.com', '6D6 khu giãn dân yên phúc', '897638891940', '2022-07-23', 'P57 A4 ngõ 120 Hoàng Quốc Việt', 'Nhân viên', '29219', 'Sacombank', '73 Kim Hoa', '17120d02-6ab5-3e43-18cb-66948daf6128', '2016-10-26 15:12:23', 'Clarence Weston', '1995-04-28 15:02:54', 'Brianna Chappell', NULL),
('7a301ea4-331e-73f6-1a77-d9ebc53aac3d', 'NV-40776', 'Nguyễn Minh Tài', '1965-10-07', 0, '0987419510', '0369878963', 'Abel@nowhere.com', '33B Phạm Ngũ Lão', '972979670451', '2017-11-10', '25 Ngõ 2 Đại Từ', 'Trường nhóm', '50026', 'MBBank', '49 Nguyễn Trung Ngạn', '142cb08f-7c31-21fa-8e90-67245e8b283e', '2022-10-05 11:44:17', 'Rachel Enriquez', '1989-12-22 04:37:00', 'Alison Abreu', NULL),
('7ad34860-1ac8-7ad7-d01d-086412a8ea97', 'NV-99406', 'Mai Thành Thông', '1953-01-12', 0, '0369989699', '0963369896', 'Barron@nowhere.com', '161 Thạnh Xuân 21', '887921362051', '2010-04-12', '47 Trần Quốc Toản', 'Trường nhóm', '09929', 'MBBank', 'Tầng 1 nhà Sunrise 3B Khu đô thị Sài Đồng', '768f8e64-7d10-20c9-967d-e8c757976496', '1970-01-01 00:00:12', 'Bennie Broussard', '1971-01-01 00:00:12', 'Alease Perales', NULL),
('7b666cc3-1b67-6037-67f6-423b4e874d0f', 'NV-05292', 'Nguyễn Thị Khuê', '1978-05-10', 1, '0369889698', '0986369879', 'Ruffin@nowhere.com', 'số 3 ngách 10 ngõ 122 phố vĩnh tuy', '729539089420', '2012-06-30', '94 việt hưng', 'Giám đốc', '80270', 'MBBank', '279 Ấp Chiến Lược', '469b3ece-744a-45d5-957d-e8c757976496', '2005-08-29 06:57:02', 'Adaline Ashley', '1974-06-29 23:31:01', 'Alexandria Mendenhall', NULL),
('7bd9cf39-3f55-3a7b-0035-60b3ebf808a9', 'NV-25278', 'Nông Ánh Quế', '1953-01-07', 2, '0396398789', '0369889698', 'Sima_Call6@example.com', 'E39 Khu Đấu Giá Ngô Thì Nhậm', '604933541621', '2012-11-13', '151 Nguyễn Duy Cung', 'Nhân viên', '25316', 'ACBank', '525 Phúc Diễn', '469b3ece-744a-45d5-957d-e8c757976496', '1970-01-01 00:00:07', 'Cleotilde Gorman', '1971-01-01 00:00:07', 'Porsha Minton', NULL),
('7c1ae6ac-6c72-7436-2dc2-579daad24557', 'NV-06877', 'Hoàng Văn Minh', '1964-12-21', 0, '0396398789', '0369878969', 'Buck.Y_Agnew669@example.com', 'Số nhà 182 Bồ Đề', '508015885400', '2012-12-03', 'Số 8 Tân Thới Nhất 12', 'Trường nhóm', '80516', 'ACBank', '161 Thạnh Xuân 21', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '2011-12-08 18:51:52', 'Aline Carlos', '2007-02-27 06:30:23', 'Parthenia Pomeroy', NULL),
('7e61a689-2cd8-340e-2677-d9ebc53aac3d', 'NV-81531', 'Mai Văn Minh', '1961-02-10', 0, '0396398789', '0986369879', 'uafuxcvn.bjehl@example.com', '413/22 Lê Văn Sỹ', '208041217120', '2012-05-04', '31/250 kim giang', 'Nhân viên', '65344', 'VPank', '48/299 Hoàng Mai', '17120d02-6ab5-3e43-18cb-66948daf6128', '2008-10-28 19:11:23', 'Cheryll Nesmith', '1991-03-22 09:01:15', 'Zandra Burns', NULL),
('7f1b6c7c-2b74-3ebb-31c2-579daad24557', 'NV-27975', 'Vũ Văn Nhật', '1961-04-25', 0, '0987419510', '0987419510', 'CaritaHSchmitz@nowhere.com', '146 Phạm Văn Chiêu', '378236017011', '2018-12-13', 'số 3 Phùng Khoang', 'Bảo vệ', '94768', 'Sacombank', '212/204 Nguyễn Văn Nguyễn', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '1970-01-01 00:50:37', 'Beverlee Aponte', '1971-01-01 00:50:37', 'Whitney Sands', NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;