//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Testamis.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Testamis.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi vui lòng đợi .
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại.
        /// </summary>
        public static string ErrorMsg_Check {
            get {
                return ResourceManager.GetString("ErrorMsg_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không đúng định dạng.
        /// </summary>
        public static string ErrorMsg_CustomValidate {
            get {
                return ResourceManager.GetString("ErrorMsg_CustomValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh lớn hơn ngày hiện tại.
        /// </summary>
        public static string ErrorMsg_DataOfBirth {
            get {
                return ResourceManager.GetString("ErrorMsg_DataOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID không tồn tại.
        /// </summary>
        public static string ErrorMsg_Filter {
            get {
                return ResourceManager.GetString("ErrorMsg_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi lấy tất cả danh sách.
        /// </summary>
        public static string ErrorMsg_GetAll {
            get {
                return ResourceManager.GetString("ErrorMsg_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi lấy đối tượng theo id khi gọi vào DL.
        /// </summary>
        public static string ErrorMsg_GetByIdByDL {
            get {
                return ResourceManager.GetString("ErrorMsg_GetByIdByDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp lớn hơn ngày hiện tại.
        /// </summary>
        public static string ErrorMsg_IdentityDate {
            get {
                return ResourceManager.GetString("ErrorMsg_IdentityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi thêm mới khi gọi vào DL.
        /// </summary>
        public static string ErrorMsg_InsertByDL {
            get {
                return ResourceManager.GetString("ErrorMsg_InsertByDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi sửa khi gọi vào DL.
        /// </summary>
        public static string ErrorMsg_UpdateByDL {
            get {
                return ResourceManager.GetString("ErrorMsg_UpdateByDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string ErrorMsg_Validate {
            get {
                return ResourceManager.GetString("ErrorMsg_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống.
        /// </summary>
        public static string ErrorMsg_ValidateEmpCode {
            get {
                return ResourceManager.GetString("ErrorMsg_ValidateEmpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi xóa nhân viên.
        /// </summary>
        public static string ErrorMsgDev_DeleteEmployee {
            get {
                return ResourceManager.GetString("ErrorMsgDev_DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi xóa danh sách nhân viên.
        /// </summary>
        public static string ErrorMsgDev_DeleteEmployees {
            get {
                return ResourceManager.GetString("ErrorMsgDev_DeleteEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi xuất danh sách đơn công tác.
        /// </summary>
        public static string ErrorMsgDev_Export {
            get {
                return ResourceManager.GetString("ErrorMsgDev_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tìm kiếm theo id.
        /// </summary>
        public static string ErrorMsgDev_Filter {
            get {
                return ResourceManager.GetString("ErrorMsgDev_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi lấy thông tin thông tin viên id.
        /// </summary>
        public static string ErrorMsgDev_GetEmployeeByID {
            get {
                return ResourceManager.GetString("ErrorMsgDev_GetEmployeeByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi thêm nhân viên.
        /// </summary>
        public static string ErrorMsgDev_Insert {
            get {
                return ResourceManager.GetString("ErrorMsgDev_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi sửa nhân viên.
        /// </summary>
        public static string ErrorMsgDev_Update {
            get {
                return ResourceManager.GetString("ErrorMsgDev_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên không tồn.
        /// </summary>
        public static string ErrorMsgUser_CRUD {
            get {
                return ResourceManager.GetString("ErrorMsgUser_CRUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng file tải lên vượt quá {0}..
        /// </summary>
        public static string FileCapacityExceeded {
            get {
                return ResourceManager.GetString("FileCapacityExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không có dữ liệu..
        /// </summary>
        public static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\MISA\ImportExcel\Kết quả kiểm tra.xlsx.
        /// </summary>
        public static string FileExportEmployeeValidate {
            get {
                return ResourceManager.GetString("FileExportEmployeeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không đúng định dạng..
        /// </summary>
        public static string FileNcorrectFormat {
            get {
                return ResourceManager.GetString("FileNcorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NameSheetExportEmployeeValidate {
            get {
                return ResourceManager.GetString("NameSheetExportEmployeeValidate", resourceCulture);
            }
        }
    }
}
